root = "."
tmp_dir = "tmp"

[build]
cmd = "CGO_ENABLED=0 go build -o ./tmp/transpondarrd ./cmd/transpondarrd"
bin = "./tmp/transpondarrd"
include_ext = ["go", "sql", "html"]
exclude_dir = ["tmp", "frontend", "web/dist", "dist", "data"]
delay = 500

[misc]
clean_on_exit = true
