// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocklist.sql

package db

import (
	"context"
	"database/sql"
)

const deleteBlocklistEntry = `-- name: DeleteBlocklistEntry :execrows
DELETE FROM release_blocklist
WHERE id = ? AND series_id = ?
`

type DeleteBlocklistEntryParams struct {
	ID       int64 `json:"id"`
	SeriesID int64 `json:"series_id"`
}

// Scoped to the series so an unblock cannot reach another series' entry.
func (q *Queries) DeleteBlocklistEntry(ctx context.Context, arg DeleteBlocklistEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBlocklistEntry, arg.ID, arg.SeriesID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBlocklistEntry = `-- name: GetBlocklistEntry :one
SELECT id, series_id, info_hash, release_title, normalized_title, reason, failures, blocked_until, created_at, updated_at
FROM release_blocklist
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetBlocklistEntry(ctx context.Context, id int64) (ReleaseBlocklist, error) {
	row := q.db.QueryRowContext(ctx, getBlocklistEntry, id)
	var i ReleaseBlocklist
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.InfoHash,
		&i.ReleaseTitle,
		&i.NormalizedTitle,
		&i.Reason,
		&i.Failures,
		&i.BlockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveBlocklist = `-- name: ListActiveBlocklist :many
SELECT id, series_id, info_hash, release_title, normalized_title, reason, failures, blocked_until, created_at, updated_at
FROM release_blocklist
WHERE series_id = ? AND (blocked_until IS NULL OR blocked_until > ?)
ORDER BY updated_at DESC
`

type ListActiveBlocklistParams struct {
	SeriesID     int64          `json:"series_id"`
	BlockedUntil sql.NullString `json:"blocked_until"`
}

// What decide must refuse right now. A NULL blocked_until is permanent.
func (q *Queries) ListActiveBlocklist(ctx context.Context, arg ListActiveBlocklistParams) ([]ReleaseBlocklist, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBlocklist, arg.SeriesID, arg.BlockedUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseBlocklist{}
	for rows.Next() {
		var i ReleaseBlocklist
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.InfoHash,
			&i.ReleaseTitle,
			&i.NormalizedTitle,
			&i.Reason,
			&i.Failures,
			&i.BlockedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocklistBySeries = `-- name: ListBlocklistBySeries :many
SELECT id, series_id, info_hash, release_title, normalized_title, reason, failures, blocked_until, created_at, updated_at
FROM release_blocklist
WHERE series_id = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListBlocklistBySeries(ctx context.Context, seriesID int64) ([]ReleaseBlocklist, error) {
	rows, err := q.db.QueryContext(ctx, listBlocklistBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseBlocklist{}
	for rows.Next() {
		var i ReleaseBlocklist
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.InfoHash,
			&i.ReleaseTitle,
			&i.NormalizedTitle,
			&i.Reason,
			&i.Failures,
			&i.BlockedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBlocklistEntry = `-- name: UpsertBlocklistEntry :one

INSERT INTO release_blocklist (series_id, info_hash, release_title, normalized_title, reason, blocked_until)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (series_id, normalized_title) DO UPDATE SET
    info_hash     = excluded.info_hash,
    release_title = excluded.release_title,
    reason        = excluded.reason,
    blocked_until = excluded.blocked_until,
    failures      = release_blocklist.failures + 1,
    updated_at    = datetime('now')
RETURNING id, series_id, info_hash, release_title, normalized_title, reason, failures, blocked_until, created_at, updated_at
`

type UpsertBlocklistEntryParams struct {
	SeriesID        int64          `json:"series_id"`
	InfoHash        string         `json:"info_hash"`
	ReleaseTitle    string         `json:"release_title"`
	NormalizedTitle string         `json:"normalized_title"`
	Reason          string         `json:"reason"`
	BlockedUntil    sql.NullString `json:"blocked_until"`
}

// NOTE: keep comments in this file ASCII-only. sqlc's sqlite codegen miscounts
// byte vs. rune offsets and a multi-byte character in a doc comment silently
// truncates the emitted SQL. See CLAUDE.md.
// A repeat failure of the same release bumps the existing row so the escalating
// expiry can see the count; hash, reason and expiry take the latest attempt's.
func (q *Queries) UpsertBlocklistEntry(ctx context.Context, arg UpsertBlocklistEntryParams) (ReleaseBlocklist, error) {
	row := q.db.QueryRowContext(ctx, upsertBlocklistEntry,
		arg.SeriesID,
		arg.InfoHash,
		arg.ReleaseTitle,
		arg.NormalizedTitle,
		arg.Reason,
		arg.BlockedUntil,
	)
	var i ReleaseBlocklist
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.InfoHash,
		&i.ReleaseTitle,
		&i.NormalizedTitle,
		&i.Reason,
		&i.Failures,
		&i.BlockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
