// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grabs.sql

package db

import (
	"context"
	"database/sql"
)

const listGrabsByInfoHash = `-- name: ListGrabsByInfoHash :many
SELECT id, wanted_item_id, info_hash, release_title, status, created_at, missing_since
FROM grabs
WHERE info_hash = ?
`

func (q *Queries) ListGrabsByInfoHash(ctx context.Context, infoHash string) ([]Grab, error) {
	rows, err := q.db.QueryContext(ctx, listGrabsByInfoHash, infoHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Grab{}
	for rows.Next() {
		var i Grab
		if err := rows.Scan(
			&i.ID,
			&i.WantedItemID,
			&i.InfoHash,
			&i.ReleaseTitle,
			&i.Status,
			&i.CreatedAt,
			&i.MissingSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrabsBySeries = `-- name: ListGrabsBySeries :many
SELECT g.id, g.wanted_item_id, g.info_hash, g.release_title, g.status, g.created_at, g.missing_since
FROM grabs g
JOIN wanted_items w ON w.id = g.wanted_item_id
WHERE w.series_id = ?
ORDER BY g.created_at DESC
`

func (q *Queries) ListGrabsBySeries(ctx context.Context, seriesID int64) ([]Grab, error) {
	rows, err := q.db.QueryContext(ctx, listGrabsBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Grab{}
	for rows.Next() {
		var i Grab
		if err := rows.Scan(
			&i.ID,
			&i.WantedItemID,
			&i.InfoHash,
			&i.ReleaseTitle,
			&i.Status,
			&i.CreatedAt,
			&i.MissingSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrabsByStatus = `-- name: ListGrabsByStatus :many
SELECT
    g.id, g.wanted_item_id, g.info_hash, g.release_title, g.status,
    g.missing_since,
    w.number AS item_number,
    w.kind   AS item_kind,
    s.id     AS series_id,
    s.title  AS series_title,
    s.format AS series_format
FROM grabs g
JOIN wanted_items w ON w.id = g.wanted_item_id
JOIN series s ON s.id = w.series_id
WHERE g.status = ?
ORDER BY g.info_hash
`

type ListGrabsByStatusRow struct {
	ID           int64          `json:"id"`
	WantedItemID int64          `json:"wanted_item_id"`
	InfoHash     string         `json:"info_hash"`
	ReleaseTitle string         `json:"release_title"`
	Status       string         `json:"status"`
	MissingSince sql.NullString `json:"missing_since"`
	ItemNumber   sql.NullInt64  `json:"item_number"`
	ItemKind     string         `json:"item_kind"`
	SeriesID     int64          `json:"series_id"`
	SeriesTitle  string         `json:"series_title"`
	SeriesFormat string         `json:"series_format"`
}

func (q *Queries) ListGrabsByStatus(ctx context.Context, status string) ([]ListGrabsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listGrabsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrabsByStatusRow{}
	for rows.Next() {
		var i ListGrabsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.WantedItemID,
			&i.InfoHash,
			&i.ReleaseTitle,
			&i.Status,
			&i.MissingSince,
			&i.ItemNumber,
			&i.ItemKind,
			&i.SeriesID,
			&i.SeriesTitle,
			&i.SeriesFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGrabMissingSince = `-- name: SetGrabMissingSince :exec
UPDATE grabs SET missing_since = ? WHERE id = ?
`

type SetGrabMissingSinceParams struct {
	MissingSince sql.NullString `json:"missing_since"`
	ID           int64          `json:"id"`
}

// The caller supplies the timestamp in SQLite's datetime('now') format, so
// writing and comparing it use one clock.
// NOTE: keep comments here ASCII-only. sqlc's sqlite codegen miscounts byte vs.
// rune offsets and silently truncates the emitted SQL on a multi-byte character.
func (q *Queries) SetGrabMissingSince(ctx context.Context, arg SetGrabMissingSinceParams) error {
	_, err := q.db.ExecContext(ctx, setGrabMissingSince, arg.MissingSince, arg.ID)
	return err
}

const setGrabStatus = `-- name: SetGrabStatus :exec
UPDATE grabs SET status = ? WHERE id = ?
`

type SetGrabStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetGrabStatus(ctx context.Context, arg SetGrabStatusParams) error {
	_, err := q.db.ExecContext(ctx, setGrabStatus, arg.Status, arg.ID)
	return err
}

const upsertGrab = `-- name: UpsertGrab :one
INSERT INTO grabs (wanted_item_id, info_hash, release_title, status)
VALUES (?, ?, ?, ?)
ON CONFLICT (wanted_item_id) DO UPDATE SET
    info_hash     = excluded.info_hash,
    release_title = excluded.release_title,
    status        = excluded.status,
    created_at    = datetime('now'),
    -- A re-grab is a fresh download; the previous attempt's stamp must not count.
    missing_since = NULL
RETURNING id, wanted_item_id, info_hash, release_title, status, created_at, missing_since
`

type UpsertGrabParams struct {
	WantedItemID int64  `json:"wanted_item_id"`
	InfoHash     string `json:"info_hash"`
	ReleaseTitle string `json:"release_title"`
	Status       string `json:"status"`
}

func (q *Queries) UpsertGrab(ctx context.Context, arg UpsertGrabParams) (Grab, error) {
	row := q.db.QueryRowContext(ctx, upsertGrab,
		arg.WantedItemID,
		arg.InfoHash,
		arg.ReleaseTitle,
		arg.Status,
	)
	var i Grab
	err := row.Scan(
		&i.ID,
		&i.WantedItemID,
		&i.InfoHash,
		&i.ReleaseTitle,
		&i.Status,
		&i.CreatedAt,
		&i.MissingSince,
	)
	return i, err
}
