// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grab_events.sql

package db

import (
	"context"
)

const appendGrabEvent = `-- name: AppendGrabEvent :exec

INSERT INTO grab_events (series_id, wanted_item_id, item_number, item_kind, info_hash, release_title, event, detail)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type AppendGrabEventParams struct {
	SeriesID     int64  `json:"series_id"`
	WantedItemID int64  `json:"wanted_item_id"`
	ItemNumber   int64  `json:"item_number"`
	ItemKind     string `json:"item_kind"`
	InfoHash     string `json:"info_hash"`
	ReleaseTitle string `json:"release_title"`
	Event        string `json:"event"`
	Detail       string `json:"detail"`
}

// NOTE: keep comments here ASCII-only. sqlc's sqlite codegen miscounts byte vs.
// rune offsets and silently truncates the emitted SQL on a multi-byte character.
func (q *Queries) AppendGrabEvent(ctx context.Context, arg AppendGrabEventParams) error {
	_, err := q.db.ExecContext(ctx, appendGrabEvent,
		arg.SeriesID,
		arg.WantedItemID,
		arg.ItemNumber,
		arg.ItemKind,
		arg.InfoHash,
		arg.ReleaseTitle,
		arg.Event,
		arg.Detail,
	)
	return err
}

const listGrabEventsPage = `-- name: ListGrabEventsPage :many
SELECT e.id, e.series_id, e.wanted_item_id, e.item_number, e.item_kind, e.info_hash, e.release_title, e.event, e.detail, e.created_at, s.title AS title_name
FROM grab_events e
JOIN series s ON s.id = e.series_id
ORDER BY e.created_at DESC, e.id DESC
LIMIT ?
`

type ListGrabEventsPageRow struct {
	ID           int64  `json:"id"`
	SeriesID     int64  `json:"series_id"`
	WantedItemID int64  `json:"wanted_item_id"`
	ItemNumber   int64  `json:"item_number"`
	ItemKind     string `json:"item_kind"`
	InfoHash     string `json:"info_hash"`
	ReleaseTitle string `json:"release_title"`
	Event        string `json:"event"`
	Detail       string `json:"detail"`
	CreatedAt    string `json:"created_at"`
	TitleName    string `json:"title_name"`
}

func (q *Queries) ListGrabEventsPage(ctx context.Context, limit int64) ([]ListGrabEventsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listGrabEventsPage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrabEventsPageRow{}
	for rows.Next() {
		var i ListGrabEventsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.WantedItemID,
			&i.ItemNumber,
			&i.ItemKind,
			&i.InfoHash,
			&i.ReleaseTitle,
			&i.Event,
			&i.Detail,
			&i.CreatedAt,
			&i.TitleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrabEventsPageBefore = `-- name: ListGrabEventsPageBefore :many
SELECT e.id, e.series_id, e.wanted_item_id, e.item_number, e.item_kind, e.info_hash, e.release_title, e.event, e.detail, e.created_at, s.title AS title_name
FROM grab_events e
JOIN series s ON s.id = e.series_id
WHERE e.created_at < ? OR (e.created_at = ? AND e.id < ?)
ORDER BY e.created_at DESC, e.id DESC
LIMIT ?
`

type ListGrabEventsPageBeforeParams struct {
	CreatedAt   string `json:"created_at"`
	CreatedAt_2 string `json:"created_at_2"`
	ID          int64  `json:"id"`
	Limit       int64  `json:"limit"`
}

type ListGrabEventsPageBeforeRow struct {
	ID           int64  `json:"id"`
	SeriesID     int64  `json:"series_id"`
	WantedItemID int64  `json:"wanted_item_id"`
	ItemNumber   int64  `json:"item_number"`
	ItemKind     string `json:"item_kind"`
	InfoHash     string `json:"info_hash"`
	ReleaseTitle string `json:"release_title"`
	Event        string `json:"event"`
	Detail       string `json:"detail"`
	CreatedAt    string `json:"created_at"`
	TitleName    string `json:"title_name"`
}

// Keyset cursor on (created_at, id); the timestamp is passed twice because this
// dialect rejects named params.
func (q *Queries) ListGrabEventsPageBefore(ctx context.Context, arg ListGrabEventsPageBeforeParams) ([]ListGrabEventsPageBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listGrabEventsPageBefore,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrabEventsPageBeforeRow{}
	for rows.Next() {
		var i ListGrabEventsPageBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.WantedItemID,
			&i.ItemNumber,
			&i.ItemKind,
			&i.InfoHash,
			&i.ReleaseTitle,
			&i.Event,
			&i.Detail,
			&i.CreatedAt,
			&i.TitleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTitleGrabEvents = `-- name: ListTitleGrabEvents :many
SELECT id, series_id, wanted_item_id, item_number, item_kind, info_hash, release_title, event, detail, created_at
FROM grab_events
WHERE series_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListTitleGrabEvents(ctx context.Context, seriesID int64) ([]GrabEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTitleGrabEvents, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GrabEvent{}
	for rows.Next() {
		var i GrabEvent
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.WantedItemID,
			&i.ItemNumber,
			&i.ItemKind,
			&i.InfoHash,
			&i.ReleaseTitle,
			&i.Event,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
