// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package db

import (
	"context"
	"database/sql"
)

const getCachedMetadata = `-- name: GetCachedMetadata :one
SELECT provider, provider_id, status, format, episode_count, title, raw, fetched_at
FROM metadata_cache
WHERE provider = ? AND provider_id = ?
LIMIT 1
`

type GetCachedMetadataParams struct {
	Provider   string `json:"provider"`
	ProviderID int64  `json:"provider_id"`
}

func (q *Queries) GetCachedMetadata(ctx context.Context, arg GetCachedMetadataParams) (MetadataCache, error) {
	row := q.db.QueryRowContext(ctx, getCachedMetadata, arg.Provider, arg.ProviderID)
	var i MetadataCache
	err := row.Scan(
		&i.Provider,
		&i.ProviderID,
		&i.Status,
		&i.Format,
		&i.EpisodeCount,
		&i.Title,
		&i.Raw,
		&i.FetchedAt,
	)
	return i, err
}

const upsertMetadata = `-- name: UpsertMetadata :exec
INSERT INTO metadata_cache (provider, provider_id, status, format, episode_count, title, raw, fetched_at)
VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT (provider, provider_id) DO UPDATE SET
    status        = excluded.status,
    format        = excluded.format,
    episode_count = excluded.episode_count,
    title         = excluded.title,
    raw           = excluded.raw,
    fetched_at    = excluded.fetched_at
`

type UpsertMetadataParams struct {
	Provider     string         `json:"provider"`
	ProviderID   int64          `json:"provider_id"`
	Status       sql.NullString `json:"status"`
	Format       sql.NullString `json:"format"`
	EpisodeCount sql.NullInt64  `json:"episode_count"`
	Title        sql.NullString `json:"title"`
	Raw          string         `json:"raw"`
}

func (q *Queries) UpsertMetadata(ctx context.Context, arg UpsertMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertMetadata,
		arg.Provider,
		arg.ProviderID,
		arg.Status,
		arg.Format,
		arg.EpisodeCount,
		arg.Title,
		arg.Raw,
	)
	return err
}
