// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Grab struct {
	ID           int64          `json:"id"`
	WantedItemID int64          `json:"wanted_item_id"`
	InfoHash     string         `json:"info_hash"`
	ReleaseTitle string         `json:"release_title"`
	Status       string         `json:"status"`
	CreatedAt    string         `json:"created_at"`
	MissingSince sql.NullString `json:"missing_since"`
	LastError    sql.NullString `json:"last_error"`
}

type GrabEvent struct {
	ID           int64  `json:"id"`
	SeriesID     int64  `json:"series_id"`
	WantedItemID int64  `json:"wanted_item_id"`
	ItemNumber   int64  `json:"item_number"`
	ItemKind     string `json:"item_kind"`
	InfoHash     string `json:"info_hash"`
	ReleaseTitle string `json:"release_title"`
	Event        string `json:"event"`
	Detail       string `json:"detail"`
	CreatedAt    string `json:"created_at"`
}

type MetadataCache struct {
	Provider     string         `json:"provider"`
	ProviderID   int64          `json:"provider_id"`
	Status       sql.NullString `json:"status"`
	Format       sql.NullString `json:"format"`
	EpisodeCount sql.NullInt64  `json:"episode_count"`
	Title        sql.NullString `json:"title"`
	Raw          string         `json:"raw"`
	FetchedAt    string         `json:"fetched_at"`
}

type PassOutcome struct {
	WantedItemID int64          `json:"wanted_item_id"`
	Outcome      string         `json:"outcome"`
	Source       string         `json:"source"`
	ReleaseTitle string         `json:"release_title"`
	Detail       string         `json:"detail"`
	HeldUntil    sql.NullString `json:"held_until"`
	RecordedAt   string         `json:"recorded_at"`
}

type QualityProfile struct {
	ID                   int64  `json:"id"`
	Name                 string `json:"name"`
	IsDefault            int64  `json:"is_default"`
	ResolutionOrder      string `json:"resolution_order"`
	PreferredSource      string `json:"preferred_source"`
	SubPref              string `json:"sub_pref"`
	PreferDualAudio      int64  `json:"prefer_dual_audio"`
	CodecPref            string `json:"codec_pref"`
	HardExcludes         string `json:"hard_excludes"`
	MinScore             int64  `json:"min_score"`
	CreatedAt            string `json:"created_at"`
	UpgradesEnabled      int64  `json:"upgrades_enabled"`
	CutoffScore          int64  `json:"cutoff_score"`
	UpgradeV2AboveCutoff int64  `json:"upgrade_v2_above_cutoff"`
}

type QualityProfileGroup struct {
	ID        int64  `json:"id"`
	ProfileID int64  `json:"profile_id"`
	Rank      int64  `json:"rank"`
	GroupName string `json:"group_name"`
	Blocked   int64  `json:"blocked"`
}

type ReleaseBlocklist struct {
	ID              int64          `json:"id"`
	SeriesID        int64          `json:"series_id"`
	InfoHash        string         `json:"info_hash"`
	ReleaseTitle    string         `json:"release_title"`
	NormalizedTitle string         `json:"normalized_title"`
	Reason          string         `json:"reason"`
	Failures        int64          `json:"failures"`
	BlockedUntil    sql.NullString `json:"blocked_until"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

type SeasonCache struct {
	Provider  string `json:"provider"`
	Season    string `json:"season"`
	Year      int64  `json:"year"`
	Raw       string `json:"raw"`
	FetchedAt string `json:"fetched_at"`
}

type Series struct {
	ID               int64          `json:"id"`
	AnilistID        sql.NullInt64  `json:"anilist_id"`
	Title            string         `json:"title"`
	Format           string         `json:"format"`
	Monitored        int64          `json:"monitored"`
	CreatedAt        string         `json:"created_at"`
	QualityProfileID int64          `json:"quality_profile_id"`
	AiringSyncedAt   sql.NullString `json:"airing_synced_at"`
	PinnedGroup      sql.NullString `json:"pinned_group"`
	LastSearchedAt   sql.NullString `json:"last_searched_at"`
	SearchBackoff    int64          `json:"search_backoff"`
	NextSearchAt     sql.NullString `json:"next_search_at"`
	PinDelayHours    sql.NullInt64  `json:"pin_delay_hours"`
	SearchEpoch      int64          `json:"search_epoch"`
}

type Session struct {
	Token     string `json:"token"`
	Username  string `json:"username"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type Setting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type WantedItem struct {
	ID               int64          `json:"id"`
	SeriesID         int64          `json:"series_id"`
	Kind             string         `json:"kind"`
	Number           sql.NullInt64  `json:"number"`
	Title            sql.NullString `json:"title"`
	Have             int64          `json:"have"`
	AirsAt           sql.NullString `json:"airs_at"`
	HeldReleaseTitle string         `json:"held_release_title"`
}
