// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Grab struct {
	ID           int64          `json:"id"`
	WantedItemID int64          `json:"wanted_item_id"`
	InfoHash     string         `json:"info_hash"`
	ReleaseTitle string         `json:"release_title"`
	Status       string         `json:"status"`
	CreatedAt    string         `json:"created_at"`
	MissingSince sql.NullString `json:"missing_since"`
}

type MetadataCache struct {
	Provider     string         `json:"provider"`
	ProviderID   int64          `json:"provider_id"`
	Status       sql.NullString `json:"status"`
	Format       sql.NullString `json:"format"`
	EpisodeCount sql.NullInt64  `json:"episode_count"`
	Title        sql.NullString `json:"title"`
	Raw          string         `json:"raw"`
	FetchedAt    string         `json:"fetched_at"`
}

type Series struct {
	ID        int64         `json:"id"`
	AnilistID sql.NullInt64 `json:"anilist_id"`
	Title     string        `json:"title"`
	Format    string        `json:"format"`
	Monitored int64         `json:"monitored"`
	CreatedAt string        `json:"created_at"`
}

type Session struct {
	Token     string `json:"token"`
	Username  string `json:"username"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type Setting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type WantedItem struct {
	ID       int64          `json:"id"`
	SeriesID int64          `json:"series_id"`
	Kind     string         `json:"kind"`
	Number   sql.NullInt64  `json:"number"`
	Title    sql.NullString `json:"title"`
	Have     int64          `json:"have"`
}
