// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pass_outcomes.sql

package db

import (
	"context"
	"database/sql"
)

const getPassOutcome = `-- name: GetPassOutcome :one
SELECT wanted_item_id, outcome, source, release_title, detail, held_until, recorded_at FROM pass_outcomes WHERE wanted_item_id = ?
`

// One item's stored outcome. The listing reads these through a join; this exists
// for tests and for a single-item lookup.
func (q *Queries) GetPassOutcome(ctx context.Context, wantedItemID int64) (PassOutcome, error) {
	row := q.db.QueryRowContext(ctx, getPassOutcome, wantedItemID)
	var i PassOutcome
	err := row.Scan(
		&i.WantedItemID,
		&i.Outcome,
		&i.Source,
		&i.ReleaseTitle,
		&i.Detail,
		&i.HeldUntil,
		&i.RecordedAt,
	)
	return i, err
}

const upsertPassOutcome = `-- name: UpsertPassOutcome :exec

INSERT INTO pass_outcomes (wanted_item_id, outcome, source, release_title, detail, held_until, recorded_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (wanted_item_id) DO UPDATE SET
    outcome       = excluded.outcome,
    source        = excluded.source,
    release_title = excluded.release_title,
    detail        = excluded.detail,
    held_until    = excluded.held_until,
    recorded_at   = excluded.recorded_at
`

type UpsertPassOutcomeParams struct {
	WantedItemID int64          `json:"wanted_item_id"`
	Outcome      string         `json:"outcome"`
	Source       string         `json:"source"`
	ReleaseTitle string         `json:"release_title"`
	Detail       string         `json:"detail"`
	HeldUntil    sql.NullString `json:"held_until"`
	RecordedAt   string         `json:"recorded_at"`
}

// What the last pass decided about one wanted item (issue #181).
// NOTE: keep comments in this file ASCII-only. sqlc's sqlite codegen miscounts
// byte vs. rune offsets and a multi-byte character in a doc comment silently
// truncates the emitted SQL. See CLAUDE.md.
// One row per item, replaced in place. Every column takes the new pass's value
// so an outcome carrying no hold clears a stale held_until, rather than leaving
// a closed pin window attached to a decision that no longer mentions it.
func (q *Queries) UpsertPassOutcome(ctx context.Context, arg UpsertPassOutcomeParams) error {
	_, err := q.db.ExecContext(ctx, upsertPassOutcome,
		arg.WantedItemID,
		arg.Outcome,
		arg.Source,
		arg.ReleaseTitle,
		arg.Detail,
		arg.HeldUntil,
		arg.RecordedAt,
	)
	return err
}
