// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"
)

const addProfileGroup = `-- name: AddProfileGroup :one
INSERT INTO quality_profile_groups (profile_id, rank, group_name, blocked)
VALUES (?, ?, ?, ?)
RETURNING id, profile_id, rank, group_name, blocked
`

type AddProfileGroupParams struct {
	ProfileID int64  `json:"profile_id"`
	Rank      int64  `json:"rank"`
	GroupName string `json:"group_name"`
	Blocked   int64  `json:"blocked"`
}

func (q *Queries) AddProfileGroup(ctx context.Context, arg AddProfileGroupParams) (QualityProfileGroup, error) {
	row := q.db.QueryRowContext(ctx, addProfileGroup,
		arg.ProfileID,
		arg.Rank,
		arg.GroupName,
		arg.Blocked,
	)
	var i QualityProfileGroup
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Rank,
		&i.GroupName,
		&i.Blocked,
	)
	return i, err
}

const countSeriesByProfile = `-- name: CountSeriesByProfile :one
SELECT COUNT(*)
FROM series
WHERE quality_profile_id = ?
`

func (q *Queries) CountSeriesByProfile(ctx context.Context, qualityProfileID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSeriesByProfile, qualityProfileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQualityProfile = `-- name: CreateQualityProfile :one
INSERT INTO quality_profiles (name, resolution_order, preferred_source, sub_pref, prefer_dual_audio, codec_pref, hard_excludes, min_score)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, is_default, resolution_order, preferred_source, sub_pref, prefer_dual_audio, codec_pref, hard_excludes, min_score, created_at
`

type CreateQualityProfileParams struct {
	Name            string `json:"name"`
	ResolutionOrder string `json:"resolution_order"`
	PreferredSource string `json:"preferred_source"`
	SubPref         string `json:"sub_pref"`
	PreferDualAudio int64  `json:"prefer_dual_audio"`
	CodecPref       string `json:"codec_pref"`
	HardExcludes    string `json:"hard_excludes"`
	MinScore        int64  `json:"min_score"`
}

func (q *Queries) CreateQualityProfile(ctx context.Context, arg CreateQualityProfileParams) (QualityProfile, error) {
	row := q.db.QueryRowContext(ctx, createQualityProfile,
		arg.Name,
		arg.ResolutionOrder,
		arg.PreferredSource,
		arg.SubPref,
		arg.PreferDualAudio,
		arg.CodecPref,
		arg.HardExcludes,
		arg.MinScore,
	)
	var i QualityProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.ResolutionOrder,
		&i.PreferredSource,
		&i.SubPref,
		&i.PreferDualAudio,
		&i.CodecPref,
		&i.HardExcludes,
		&i.MinScore,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProfileGroups = `-- name: DeleteProfileGroups :exec
DELETE FROM quality_profile_groups
WHERE profile_id = ?
`

func (q *Queries) DeleteProfileGroups(ctx context.Context, profileID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProfileGroups, profileID)
	return err
}

const deleteQualityProfile = `-- name: DeleteQualityProfile :exec
DELETE FROM quality_profiles
WHERE id = ? AND is_default = 0
`

func (q *Queries) DeleteQualityProfile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteQualityProfile, id)
	return err
}

const getDefaultQualityProfile = `-- name: GetDefaultQualityProfile :one
SELECT id, name, is_default, resolution_order, preferred_source, sub_pref, prefer_dual_audio, codec_pref, hard_excludes, min_score, created_at
FROM quality_profiles
WHERE is_default = 1
LIMIT 1
`

func (q *Queries) GetDefaultQualityProfile(ctx context.Context) (QualityProfile, error) {
	row := q.db.QueryRowContext(ctx, getDefaultQualityProfile)
	var i QualityProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.ResolutionOrder,
		&i.PreferredSource,
		&i.SubPref,
		&i.PreferDualAudio,
		&i.CodecPref,
		&i.HardExcludes,
		&i.MinScore,
		&i.CreatedAt,
	)
	return i, err
}

const getQualityProfile = `-- name: GetQualityProfile :one
SELECT id, name, is_default, resolution_order, preferred_source, sub_pref, prefer_dual_audio, codec_pref, hard_excludes, min_score, created_at
FROM quality_profiles
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetQualityProfile(ctx context.Context, id int64) (QualityProfile, error) {
	row := q.db.QueryRowContext(ctx, getQualityProfile, id)
	var i QualityProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.ResolutionOrder,
		&i.PreferredSource,
		&i.SubPref,
		&i.PreferDualAudio,
		&i.CodecPref,
		&i.HardExcludes,
		&i.MinScore,
		&i.CreatedAt,
	)
	return i, err
}

const listProfileGroups = `-- name: ListProfileGroups :many
SELECT id, profile_id, rank, group_name, blocked
FROM quality_profile_groups
WHERE profile_id = ?
ORDER BY blocked, rank
`

func (q *Queries) ListProfileGroups(ctx context.Context, profileID int64) ([]QualityProfileGroup, error) {
	rows, err := q.db.QueryContext(ctx, listProfileGroups, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QualityProfileGroup{}
	for rows.Next() {
		var i QualityProfileGroup
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Rank,
			&i.GroupName,
			&i.Blocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualityProfiles = `-- name: ListQualityProfiles :many

SELECT id, name, is_default, resolution_order, preferred_source, sub_pref, prefer_dual_audio, codec_pref, hard_excludes, min_score, created_at
FROM quality_profiles
ORDER BY is_default DESC, name
`

// NOTE: keep comments in this file ASCII-only. sqlc's sqlite codegen miscounts
// byte vs. rune offsets and a multi-byte character in a doc comment silently
// truncates the emitted SQL. See CLAUDE.md.
func (q *Queries) ListQualityProfiles(ctx context.Context) ([]QualityProfile, error) {
	rows, err := q.db.QueryContext(ctx, listQualityProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QualityProfile{}
	for rows.Next() {
		var i QualityProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDefault,
			&i.ResolutionOrder,
			&i.PreferredSource,
			&i.SubPref,
			&i.PreferDualAudio,
			&i.CodecPref,
			&i.HardExcludes,
			&i.MinScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesByProfile = `-- name: ListSeriesByProfile :many
SELECT id, title
FROM series
WHERE quality_profile_id = ?
ORDER BY title
`

type ListSeriesByProfileRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) ListSeriesByProfile(ctx context.Context, qualityProfileID int64) ([]ListSeriesByProfileRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesByProfile, qualityProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeriesByProfileRow{}
	for rows.Next() {
		var i ListSeriesByProfileRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignSeriesProfile = `-- name: ReassignSeriesProfile :exec
UPDATE series
SET quality_profile_id = ?
WHERE quality_profile_id = ?
`

type ReassignSeriesProfileParams struct {
	QualityProfileID   int64 `json:"quality_profile_id"`
	QualityProfileID_2 int64 `json:"quality_profile_id_2"`
}

func (q *Queries) ReassignSeriesProfile(ctx context.Context, arg ReassignSeriesProfileParams) error {
	_, err := q.db.ExecContext(ctx, reassignSeriesProfile, arg.QualityProfileID, arg.QualityProfileID_2)
	return err
}

const setSeriesProfile = `-- name: SetSeriesProfile :exec
UPDATE series
SET quality_profile_id = ?
WHERE id = ?
`

type SetSeriesProfileParams struct {
	QualityProfileID int64 `json:"quality_profile_id"`
	ID               int64 `json:"id"`
}

func (q *Queries) SetSeriesProfile(ctx context.Context, arg SetSeriesProfileParams) error {
	_, err := q.db.ExecContext(ctx, setSeriesProfile, arg.QualityProfileID, arg.ID)
	return err
}

const updateQualityProfile = `-- name: UpdateQualityProfile :one
UPDATE quality_profiles
SET name              = ?,
    resolution_order  = ?,
    preferred_source  = ?,
    sub_pref          = ?,
    prefer_dual_audio = ?,
    codec_pref        = ?,
    hard_excludes     = ?,
    min_score         = ?
WHERE id = ?
RETURNING id, name, is_default, resolution_order, preferred_source, sub_pref, prefer_dual_audio, codec_pref, hard_excludes, min_score, created_at
`

type UpdateQualityProfileParams struct {
	Name            string `json:"name"`
	ResolutionOrder string `json:"resolution_order"`
	PreferredSource string `json:"preferred_source"`
	SubPref         string `json:"sub_pref"`
	PreferDualAudio int64  `json:"prefer_dual_audio"`
	CodecPref       string `json:"codec_pref"`
	HardExcludes    string `json:"hard_excludes"`
	MinScore        int64  `json:"min_score"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateQualityProfile(ctx context.Context, arg UpdateQualityProfileParams) (QualityProfile, error) {
	row := q.db.QueryRowContext(ctx, updateQualityProfile,
		arg.Name,
		arg.ResolutionOrder,
		arg.PreferredSource,
		arg.SubPref,
		arg.PreferDualAudio,
		arg.CodecPref,
		arg.HardExcludes,
		arg.MinScore,
		arg.ID,
	)
	var i QualityProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.ResolutionOrder,
		&i.PreferredSource,
		&i.SubPref,
		&i.PreferDualAudio,
		&i.CodecPref,
		&i.HardExcludes,
		&i.MinScore,
		&i.CreatedAt,
	)
	return i, err
}
