// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seasons.sql

package db

import (
	"context"
)

const getSeasonCache = `-- name: GetSeasonCache :one
SELECT provider, season, year, raw, fetched_at
FROM season_cache
WHERE provider = ? AND season = ? AND year = ?
LIMIT 1
`

type GetSeasonCacheParams struct {
	Provider string `json:"provider"`
	Season   string `json:"season"`
	Year     int64  `json:"year"`
}

func (q *Queries) GetSeasonCache(ctx context.Context, arg GetSeasonCacheParams) (SeasonCache, error) {
	row := q.db.QueryRowContext(ctx, getSeasonCache, arg.Provider, arg.Season, arg.Year)
	var i SeasonCache
	err := row.Scan(
		&i.Provider,
		&i.Season,
		&i.Year,
		&i.Raw,
		&i.FetchedAt,
	)
	return i, err
}

const listSeasonCache = `-- name: ListSeasonCache :many
SELECT provider, season, year, raw, fetched_at
FROM season_cache
WHERE provider = ?
ORDER BY year, season
`

func (q *Queries) ListSeasonCache(ctx context.Context, provider string) ([]SeasonCache, error) {
	rows, err := q.db.QueryContext(ctx, listSeasonCache, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SeasonCache{}
	for rows.Next() {
		var i SeasonCache
		if err := rows.Scan(
			&i.Provider,
			&i.Season,
			&i.Year,
			&i.Raw,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSeasonCache = `-- name: UpsertSeasonCache :exec
INSERT INTO season_cache (provider, season, year, raw, fetched_at)
VALUES (?, ?, ?, ?, datetime('now'))
ON CONFLICT (provider, season, year) DO UPDATE SET
    raw        = excluded.raw,
    fetched_at = excluded.fetched_at
`

type UpsertSeasonCacheParams struct {
	Provider string `json:"provider"`
	Season   string `json:"season"`
	Year     int64  `json:"year"`
	Raw      string `json:"raw"`
}

func (q *Queries) UpsertSeasonCache(ctx context.Context, arg UpsertSeasonCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertSeasonCache,
		arg.Provider,
		arg.Season,
		arg.Year,
		arg.Raw,
	)
	return err
}
