// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: series.sql

package db

import (
	"context"
	"database/sql"
)

const createSeries = `-- name: CreateSeries :one
INSERT INTO series (anilist_id, title, format, monitored)
VALUES (?, ?, ?, ?)
RETURNING id, anilist_id, title, format, monitored, created_at, quality_profile_id
`

type CreateSeriesParams struct {
	AnilistID sql.NullInt64 `json:"anilist_id"`
	Title     string        `json:"title"`
	Format    string        `json:"format"`
	Monitored int64         `json:"monitored"`
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error) {
	row := q.db.QueryRowContext(ctx, createSeries,
		arg.AnilistID,
		arg.Title,
		arg.Format,
		arg.Monitored,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.AnilistID,
		&i.Title,
		&i.Format,
		&i.Monitored,
		&i.CreatedAt,
		&i.QualityProfileID,
	)
	return i, err
}

const getSeries = `-- name: GetSeries :one
SELECT id, anilist_id, title, format, monitored, created_at, quality_profile_id
FROM series
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSeries(ctx context.Context, id int64) (Series, error) {
	row := q.db.QueryRowContext(ctx, getSeries, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.AnilistID,
		&i.Title,
		&i.Format,
		&i.Monitored,
		&i.CreatedAt,
		&i.QualityProfileID,
	)
	return i, err
}

const getSeriesByAnilistID = `-- name: GetSeriesByAnilistID :one
SELECT id, anilist_id, title, format, monitored, created_at, quality_profile_id
FROM series
WHERE anilist_id = ?
LIMIT 1
`

func (q *Queries) GetSeriesByAnilistID(ctx context.Context, anilistID sql.NullInt64) (Series, error) {
	row := q.db.QueryRowContext(ctx, getSeriesByAnilistID, anilistID)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.AnilistID,
		&i.Title,
		&i.Format,
		&i.Monitored,
		&i.CreatedAt,
		&i.QualityProfileID,
	)
	return i, err
}

const listSeries = `-- name: ListSeries :many
SELECT id, anilist_id, title, format, monitored, created_at, quality_profile_id
FROM series
ORDER BY title
`

func (q *Queries) ListSeries(ctx context.Context) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, listSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.AnilistID,
			&i.Title,
			&i.Format,
			&i.Monitored,
			&i.CreatedAt,
			&i.QualityProfileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesWithProgress = `-- name: ListSeriesWithProgress :many
SELECT
    s.id, s.anilist_id, s.title, s.format, s.monitored, s.created_at, s.quality_profile_id,
    COUNT(w.id)                            AS total_items,
    CAST(COALESCE(SUM(w.have), 0) AS INTEGER) AS have_items
FROM series s
LEFT JOIN wanted_items w ON w.series_id = s.id
GROUP BY s.id
ORDER BY s.title
`

type ListSeriesWithProgressRow struct {
	ID               int64         `json:"id"`
	AnilistID        sql.NullInt64 `json:"anilist_id"`
	Title            string        `json:"title"`
	Format           string        `json:"format"`
	Monitored        int64         `json:"monitored"`
	CreatedAt        string        `json:"created_at"`
	QualityProfileID int64         `json:"quality_profile_id"`
	TotalItems       int64         `json:"total_items"`
	HaveItems        int64         `json:"have_items"`
}

func (q *Queries) ListSeriesWithProgress(ctx context.Context) ([]ListSeriesWithProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesWithProgress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeriesWithProgressRow{}
	for rows.Next() {
		var i ListSeriesWithProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.AnilistID,
			&i.Title,
			&i.Format,
			&i.Monitored,
			&i.CreatedAt,
			&i.QualityProfileID,
			&i.TotalItems,
			&i.HaveItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSeriesMonitored = `-- name: SetSeriesMonitored :exec
UPDATE series SET monitored = ? WHERE id = ?
`

type SetSeriesMonitoredParams struct {
	Monitored int64 `json:"monitored"`
	ID        int64 `json:"id"`
}

func (q *Queries) SetSeriesMonitored(ctx context.Context, arg SetSeriesMonitoredParams) error {
	_, err := q.db.ExecContext(ctx, setSeriesMonitored, arg.Monitored, arg.ID)
	return err
}
