// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: series.sql

package db

import (
	"context"
	"database/sql"
)

const clearSeriesAiringSyncedAt = `-- name: ClearSeriesAiringSyncedAt :exec
UPDATE series SET airing_synced_at = NULL WHERE id = ?
`

// Forces the next airing pass to re-page full history, so items inserted after
// the last sync get air dates without waiting out the series' TTL.
func (q *Queries) ClearSeriesAiringSyncedAt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearSeriesAiringSyncedAt, id)
	return err
}

const createSeries = `-- name: CreateSeries :one
INSERT INTO series (provider, provider_id, title, format, monitored)
VALUES (?, ?, ?, ?, ?)
RETURNING id, provider, provider_id, title, format, monitored, created_at, quality_profile_id, airing_synced_at, pinned_group, last_searched_at, search_backoff, next_search_at, pin_delay_hours, search_epoch
`

type CreateSeriesParams struct {
	Provider   sql.NullString `json:"provider"`
	ProviderID sql.NullInt64  `json:"provider_id"`
	Title      string         `json:"title"`
	Format     string         `json:"format"`
	Monitored  int64          `json:"monitored"`
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error) {
	row := q.db.QueryRowContext(ctx, createSeries,
		arg.Provider,
		arg.ProviderID,
		arg.Title,
		arg.Format,
		arg.Monitored,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.Title,
		&i.Format,
		&i.Monitored,
		&i.CreatedAt,
		&i.QualityProfileID,
		&i.AiringSyncedAt,
		&i.PinnedGroup,
		&i.LastSearchedAt,
		&i.SearchBackoff,
		&i.NextSearchAt,
		&i.PinDelayHours,
		&i.SearchEpoch,
	)
	return i, err
}

const deleteSeries = `-- name: DeleteSeries :execrows
DELETE FROM series WHERE id = ?
`

func (q *Queries) DeleteSeries(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSeries, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSeries = `-- name: GetSeries :one
SELECT id, provider, provider_id, title, format, monitored, created_at, quality_profile_id, airing_synced_at, pinned_group, last_searched_at, search_backoff, next_search_at, pin_delay_hours, search_epoch
FROM series
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSeries(ctx context.Context, id int64) (Series, error) {
	row := q.db.QueryRowContext(ctx, getSeries, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.Title,
		&i.Format,
		&i.Monitored,
		&i.CreatedAt,
		&i.QualityProfileID,
		&i.AiringSyncedAt,
		&i.PinnedGroup,
		&i.LastSearchedAt,
		&i.SearchBackoff,
		&i.NextSearchAt,
		&i.PinDelayHours,
		&i.SearchEpoch,
	)
	return i, err
}

const getSeriesByProviderID = `-- name: GetSeriesByProviderID :one
SELECT id, provider, provider_id, title, format, monitored, created_at, quality_profile_id, airing_synced_at, pinned_group, last_searched_at, search_backoff, next_search_at, pin_delay_hours, search_epoch
FROM series
WHERE provider = ? AND provider_id = ?
LIMIT 1
`

type GetSeriesByProviderIDParams struct {
	Provider   sql.NullString `json:"provider"`
	ProviderID sql.NullInt64  `json:"provider_id"`
}

// The pair is the identity: the same id in two provider spaces is two titles.
func (q *Queries) GetSeriesByProviderID(ctx context.Context, arg GetSeriesByProviderIDParams) (Series, error) {
	row := q.db.QueryRowContext(ctx, getSeriesByProviderID, arg.Provider, arg.ProviderID)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.Title,
		&i.Format,
		&i.Monitored,
		&i.CreatedAt,
		&i.QualityProfileID,
		&i.AiringSyncedAt,
		&i.PinnedGroup,
		&i.LastSearchedAt,
		&i.SearchBackoff,
		&i.NextSearchAt,
		&i.PinDelayHours,
		&i.SearchEpoch,
	)
	return i, err
}

const listSeries = `-- name: ListSeries :many
SELECT id, provider, provider_id, title, format, monitored, created_at, quality_profile_id, airing_synced_at, pinned_group, last_searched_at, search_backoff, next_search_at, pin_delay_hours, search_epoch
FROM series
ORDER BY title
`

func (q *Queries) ListSeries(ctx context.Context) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, listSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderID,
			&i.Title,
			&i.Format,
			&i.Monitored,
			&i.CreatedAt,
			&i.QualityProfileID,
			&i.AiringSyncedAt,
			&i.PinnedGroup,
			&i.LastSearchedAt,
			&i.SearchBackoff,
			&i.NextSearchAt,
			&i.PinDelayHours,
			&i.SearchEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesDueAiringSync = `-- name: ListSeriesDueAiringSync :many
SELECT s.id, s.provider, s.provider_id, s.title, s.format, s.monitored, s.created_at, s.quality_profile_id, s.airing_synced_at, s.pinned_group, s.last_searched_at, s.search_backoff, s.next_search_at, s.pin_delay_hours, s.search_epoch
FROM series s
LEFT JOIN metadata_cache m ON m.provider = s.provider AND m.provider_id = s.provider_id
WHERE s.monitored = 1
  AND s.provider_id IS NOT NULL
  AND (
      s.airing_synced_at IS NULL
      OR s.airing_synced_at < CASE
             WHEN m.status IN ('FINISHED', 'CANCELLED') THEN ?
             ELSE ?
         END
  )
ORDER BY s.airing_synced_at IS NOT NULL, s.airing_synced_at
LIMIT ?
`

type ListSeriesDueAiringSyncParams struct {
	AiringSyncedAt   sql.NullString `json:"airing_synced_at"`
	AiringSyncedAt_2 sql.NullString `json:"airing_synced_at_2"`
	Limit            int64          `json:"limit"`
}

// Monitored series whose broadcast schedule has never been synced or has gone
// stale. A finished title's aired times are immutable, so it waits on the long
// cutoff while anything still moving waits on the short one. A series with no
// cache row has unknown status and deliberately rides the short cutoff: unknown
// is likelier a transient anomaly than a finished title, and the cost is one
// tail request per short TTL. Never-synced series sort first; the limit bounds
// how much of the request budget one pass can burn.
func (q *Queries) ListSeriesDueAiringSync(ctx context.Context, arg ListSeriesDueAiringSyncParams) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesDueAiringSync, arg.AiringSyncedAt, arg.AiringSyncedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderID,
			&i.Title,
			&i.Format,
			&i.Monitored,
			&i.CreatedAt,
			&i.QualityProfileID,
			&i.AiringSyncedAt,
			&i.PinnedGroup,
			&i.LastSearchedAt,
			&i.SearchBackoff,
			&i.NextSearchAt,
			&i.PinDelayHours,
			&i.SearchEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesDueMetadataRefresh = `-- name: ListSeriesDueMetadataRefresh :many
SELECT s.id, s.provider, s.provider_id, s.title, s.format, s.monitored, s.created_at, s.quality_profile_id, s.airing_synced_at, s.pinned_group, s.last_searched_at, s.search_backoff, s.next_search_at, s.pin_delay_hours, s.search_epoch
FROM series s
LEFT JOIN metadata_cache m ON m.provider = s.provider AND m.provider_id = s.provider_id
WHERE s.monitored = 1
  AND s.provider_id IS NOT NULL
  AND (
      m.provider_id IS NULL
      OR m.fetched_at < CASE
             WHEN m.status IN ('FINISHED', 'CANCELLED') AND m.episode_count IS NOT NULL THEN ?
             ELSE ?
         END
  )
ORDER BY m.fetched_at IS NOT NULL, m.fetched_at
LIMIT ?
`

type ListSeriesDueMetadataRefreshParams struct {
	FetchedAt   string `json:"fetched_at"`
	FetchedAt_2 string `json:"fetched_at_2"`
	Limit       int64  `json:"limit"`
}

// Monitored series whose cached title snapshot is missing or stale under the
// status-aware TTL policy. Only a finished title with a known episode count
// earns the long cutoff; anything moving, unknown, or empty rides the short
// one, mirroring the freshness rule in metadata.Cached. Never-fetched series
// sort first; the limit bounds how much of the request budget one pass burns.
func (q *Queries) ListSeriesDueMetadataRefresh(ctx context.Context, arg ListSeriesDueMetadataRefreshParams) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesDueMetadataRefresh, arg.FetchedAt, arg.FetchedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderID,
			&i.Title,
			&i.Format,
			&i.Monitored,
			&i.CreatedAt,
			&i.QualityProfileID,
			&i.AiringSyncedAt,
			&i.PinnedGroup,
			&i.LastSearchedAt,
			&i.SearchBackoff,
			&i.NextSearchAt,
			&i.PinDelayHours,
			&i.SearchEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesWithProgress = `-- name: ListSeriesWithProgress :many
SELECT
    s.id, s.provider, s.provider_id, s.title, s.format, s.monitored, s.created_at, s.quality_profile_id, s.airing_synced_at, s.pinned_group, s.last_searched_at, s.search_backoff, s.next_search_at, s.pin_delay_hours, s.search_epoch,
    COUNT(w.id)                            AS total_items,
    CAST(COALESCE(SUM(w.in_library), 0) AS INTEGER) AS in_library_items
FROM series s
LEFT JOIN wanted_items w ON w.series_id = s.id
GROUP BY s.id
ORDER BY s.title
`

type ListSeriesWithProgressRow struct {
	ID               int64          `json:"id"`
	Provider         sql.NullString `json:"provider"`
	ProviderID       sql.NullInt64  `json:"provider_id"`
	Title            string         `json:"title"`
	Format           string         `json:"format"`
	Monitored        int64          `json:"monitored"`
	CreatedAt        string         `json:"created_at"`
	QualityProfileID int64          `json:"quality_profile_id"`
	AiringSyncedAt   sql.NullString `json:"airing_synced_at"`
	PinnedGroup      sql.NullString `json:"pinned_group"`
	LastSearchedAt   sql.NullString `json:"last_searched_at"`
	SearchBackoff    int64          `json:"search_backoff"`
	NextSearchAt     sql.NullString `json:"next_search_at"`
	PinDelayHours    sql.NullInt64  `json:"pin_delay_hours"`
	SearchEpoch      int64          `json:"search_epoch"`
	TotalItems       int64          `json:"total_items"`
	InLibraryItems   int64          `json:"in_library_items"`
}

func (q *Queries) ListSeriesWithProgress(ctx context.Context) ([]ListSeriesWithProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesWithProgress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeriesWithProgressRow{}
	for rows.Next() {
		var i ListSeriesWithProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderID,
			&i.Title,
			&i.Format,
			&i.Monitored,
			&i.CreatedAt,
			&i.QualityProfileID,
			&i.AiringSyncedAt,
			&i.PinnedGroup,
			&i.LastSearchedAt,
			&i.SearchBackoff,
			&i.NextSearchAt,
			&i.PinDelayHours,
			&i.SearchEpoch,
			&i.TotalItems,
			&i.InLibraryItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackedNextAiring = `-- name: ListTrackedNextAiring :many
SELECT
    s.id,
    s.provider_id,
    s.airing_synced_at,
    w.number AS next_number,
    w.airs_at AS next_airs_at
FROM series s
LEFT JOIN wanted_items w ON w.id = (
    SELECT w2.id
    FROM wanted_items w2
    WHERE w2.series_id = s.id
      AND w2.airs_at IS NOT NULL
      AND w2.airs_at > ?
    ORDER BY w2.airs_at
    LIMIT 1
)
WHERE s.provider = ?
`

type ListTrackedNextAiringParams struct {
	AirsAt   sql.NullString `json:"airs_at"`
	Provider sql.NullString `json:"provider"`
}

type ListTrackedNextAiringRow struct {
	ID             int64          `json:"id"`
	ProviderID     sql.NullInt64  `json:"provider_id"`
	AiringSyncedAt sql.NullString `json:"airing_synced_at"`
	NextNumber     sql.NullInt64  `json:"next_number"`
	NextAirsAt     sql.NullString `json:"next_airs_at"`
}

// Discovery overlay rows: every series keyed on the given provider, joined to
// its next item scheduled after the given instant. airing_synced_at rides along
// so the caller can tell "synced, nothing upcoming" from "never synced".
func (q *Queries) ListTrackedNextAiring(ctx context.Context, arg ListTrackedNextAiringParams) ([]ListTrackedNextAiringRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrackedNextAiring, arg.AirsAt, arg.Provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackedNextAiringRow{}
	for rows.Next() {
		var i ListTrackedNextAiringRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.AiringSyncedAt,
			&i.NextNumber,
			&i.NextAirsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSeriesAiringSyncedAt = `-- name: SetSeriesAiringSyncedAt :exec
UPDATE series SET airing_synced_at = datetime('now')
WHERE id = ? AND airing_synced_at IS ?
`

type SetSeriesAiringSyncedAtParams struct {
	ID             int64          `json:"id"`
	AiringSyncedAt sql.NullString `json:"airing_synced_at"`
}

// Guarded on the value read at selection: a refresh that cleared the stamp
// mid-sync must win, so the next airing pass re-pages the grown series.
func (q *Queries) SetSeriesAiringSyncedAt(ctx context.Context, arg SetSeriesAiringSyncedAtParams) error {
	_, err := q.db.ExecContext(ctx, setSeriesAiringSyncedAt, arg.ID, arg.AiringSyncedAt)
	return err
}

const setSeriesMonitored = `-- name: SetSeriesMonitored :exec
UPDATE series SET monitored = ? WHERE id = ?
`

type SetSeriesMonitoredParams struct {
	Monitored int64 `json:"monitored"`
	ID        int64 `json:"id"`
}

func (q *Queries) SetSeriesMonitored(ctx context.Context, arg SetSeriesMonitoredParams) error {
	_, err := q.db.ExecContext(ctx, setSeriesMonitored, arg.Monitored, arg.ID)
	return err
}

const setSeriesPinnedGroup = `-- name: SetSeriesPinnedGroup :execrows
UPDATE series SET pinned_group = ?, pin_delay_hours = ? WHERE id = ?
`

type SetSeriesPinnedGroupParams struct {
	PinnedGroup   sql.NullString `json:"pinned_group"`
	PinDelayHours sql.NullInt64  `json:"pin_delay_hours"`
	ID            int64          `json:"id"`
}

// NULL clears the pin; execrows lets the handler 404 an unknown series. The
// delay rides along because it is meaningless without a group to wait for, so
// PUT-replacing one must replace the other.
func (q *Queries) SetSeriesPinnedGroup(ctx context.Context, arg SetSeriesPinnedGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSeriesPinnedGroup, arg.PinnedGroup, arg.PinDelayHours, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
