// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, username, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string `json:"token"`
	Username  string `json:"username"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.Username, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions
WHERE username = ?
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsForUser, username)
	return err
}

const getSession = `-- name: GetSession :one
SELECT username
FROM sessions
WHERE token = ? AND expires_at > datetime('now')
LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var username string
	err := row.Scan(&username)
	return username, err
}
