// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: titles.sql

package db

import (
	"context"
	"database/sql"
)

const clearTitleAiringSyncedAt = `-- name: ClearTitleAiringSyncedAt :exec
UPDATE series SET airing_synced_at = NULL WHERE id = ?
`

// Forces the next airing pass to re-page full history, so items inserted after
// the last sync get air dates without waiting out the series' TTL.
func (q *Queries) ClearTitleAiringSyncedAt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearTitleAiringSyncedAt, id)
	return err
}

const createTitle = `-- name: CreateTitle :one
INSERT INTO series (provider, provider_id, title, format, monitored, year)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, provider, provider_id, title, format, monitored, created_at, quality_profile_id, airing_synced_at, pinned_group, last_searched_at, search_backoff, next_search_at, pin_delay_hours, search_epoch, monitor_new_from, year
`

type CreateTitleParams struct {
	Provider   sql.NullString `json:"provider"`
	ProviderID sql.NullInt64  `json:"provider_id"`
	Title      string         `json:"title"`
	Format     string         `json:"format"`
	Monitored  int64          `json:"monitored"`
	Year       int64          `json:"year"`
}

// monitor_new_from is left to its schema default: an omitted sqlc params field
// would write NULL, which reads as "monitor nothing new".
func (q *Queries) CreateTitle(ctx context.Context, arg CreateTitleParams) (Series, error) {
	row := q.db.QueryRowContext(ctx, createTitle,
		arg.Provider,
		arg.ProviderID,
		arg.Title,
		arg.Format,
		arg.Monitored,
		arg.Year,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.Title,
		&i.Format,
		&i.Monitored,
		&i.CreatedAt,
		&i.QualityProfileID,
		&i.AiringSyncedAt,
		&i.PinnedGroup,
		&i.LastSearchedAt,
		&i.SearchBackoff,
		&i.NextSearchAt,
		&i.PinDelayHours,
		&i.SearchEpoch,
		&i.MonitorNewFrom,
		&i.Year,
	)
	return i, err
}

const deleteTitle = `-- name: DeleteTitle :execrows
DELETE FROM series WHERE id = ?
`

func (q *Queries) DeleteTitle(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTitle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTitle = `-- name: GetTitle :one
SELECT id, provider, provider_id, title, format, monitored, created_at, quality_profile_id, airing_synced_at, pinned_group, last_searched_at, search_backoff, next_search_at, pin_delay_hours, search_epoch, monitor_new_from, year
FROM series
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTitle(ctx context.Context, id int64) (Series, error) {
	row := q.db.QueryRowContext(ctx, getTitle, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.Title,
		&i.Format,
		&i.Monitored,
		&i.CreatedAt,
		&i.QualityProfileID,
		&i.AiringSyncedAt,
		&i.PinnedGroup,
		&i.LastSearchedAt,
		&i.SearchBackoff,
		&i.NextSearchAt,
		&i.PinDelayHours,
		&i.SearchEpoch,
		&i.MonitorNewFrom,
		&i.Year,
	)
	return i, err
}

const getTitleByProviderID = `-- name: GetTitleByProviderID :one
SELECT id, provider, provider_id, title, format, monitored, created_at, quality_profile_id, airing_synced_at, pinned_group, last_searched_at, search_backoff, next_search_at, pin_delay_hours, search_epoch, monitor_new_from, year
FROM series
WHERE provider = ? AND provider_id = ?
LIMIT 1
`

type GetTitleByProviderIDParams struct {
	Provider   sql.NullString `json:"provider"`
	ProviderID sql.NullInt64  `json:"provider_id"`
}

// The pair is the identity: the same id in two provider spaces is two titles.
func (q *Queries) GetTitleByProviderID(ctx context.Context, arg GetTitleByProviderIDParams) (Series, error) {
	row := q.db.QueryRowContext(ctx, getTitleByProviderID, arg.Provider, arg.ProviderID)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.Title,
		&i.Format,
		&i.Monitored,
		&i.CreatedAt,
		&i.QualityProfileID,
		&i.AiringSyncedAt,
		&i.PinnedGroup,
		&i.LastSearchedAt,
		&i.SearchBackoff,
		&i.NextSearchAt,
		&i.PinDelayHours,
		&i.SearchEpoch,
		&i.MonitorNewFrom,
		&i.Year,
	)
	return i, err
}

const listTitles = `-- name: ListTitles :many
SELECT id, provider, provider_id, title, format, monitored, created_at, quality_profile_id, airing_synced_at, pinned_group, last_searched_at, search_backoff, next_search_at, pin_delay_hours, search_epoch, monitor_new_from, year
FROM series
ORDER BY title
`

func (q *Queries) ListTitles(ctx context.Context) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, listTitles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderID,
			&i.Title,
			&i.Format,
			&i.Monitored,
			&i.CreatedAt,
			&i.QualityProfileID,
			&i.AiringSyncedAt,
			&i.PinnedGroup,
			&i.LastSearchedAt,
			&i.SearchBackoff,
			&i.NextSearchAt,
			&i.PinDelayHours,
			&i.SearchEpoch,
			&i.MonitorNewFrom,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTitlesDueAiringSync = `-- name: ListTitlesDueAiringSync :many
SELECT s.id, s.provider, s.provider_id, s.title, s.format, s.monitored, s.created_at, s.quality_profile_id, s.airing_synced_at, s.pinned_group, s.last_searched_at, s.search_backoff, s.next_search_at, s.pin_delay_hours, s.search_epoch, s.monitor_new_from, s.year
FROM series s
LEFT JOIN metadata_cache m ON m.provider = s.provider AND m.provider_id = s.provider_id
WHERE s.monitored = 1
  AND s.provider = ?
  AND (
      s.airing_synced_at IS NULL
      OR s.airing_synced_at < CASE
             WHEN m.status IN ('FINISHED', 'CANCELLED') THEN ?
             ELSE ?
         END
  )
ORDER BY s.airing_synced_at IS NOT NULL, s.airing_synced_at
LIMIT ?
`

type ListTitlesDueAiringSyncParams struct {
	Provider         sql.NullString `json:"provider"`
	AiringSyncedAt   sql.NullString `json:"airing_synced_at"`
	AiringSyncedAt_2 sql.NullString `json:"airing_synced_at_2"`
	Limit            int64          `json:"limit"`
}

// Monitored series whose broadcast schedule has never been synced or has gone
// stale. A finished title's aired times are immutable, so it waits on the long
// cutoff while anything still moving waits on the short one. A series with no
// cache row has unknown status and deliberately rides the short cutoff: unknown
// is likelier a transient anomaly than a finished title, and the cost is one
// tail request per short TTL. Never-synced series sort first; the limit bounds
// how much of the request budget one pass can burn. Scoped to one provider
// because the id this hands to it is only meaningful in that provider's space.
func (q *Queries) ListTitlesDueAiringSync(ctx context.Context, arg ListTitlesDueAiringSyncParams) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, listTitlesDueAiringSync,
		arg.Provider,
		arg.AiringSyncedAt,
		arg.AiringSyncedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderID,
			&i.Title,
			&i.Format,
			&i.Monitored,
			&i.CreatedAt,
			&i.QualityProfileID,
			&i.AiringSyncedAt,
			&i.PinnedGroup,
			&i.LastSearchedAt,
			&i.SearchBackoff,
			&i.NextSearchAt,
			&i.PinDelayHours,
			&i.SearchEpoch,
			&i.MonitorNewFrom,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTitlesDueMetadataRefresh = `-- name: ListTitlesDueMetadataRefresh :many
SELECT s.id, s.provider, s.provider_id, s.title, s.format, s.monitored, s.created_at, s.quality_profile_id, s.airing_synced_at, s.pinned_group, s.last_searched_at, s.search_backoff, s.next_search_at, s.pin_delay_hours, s.search_epoch, s.monitor_new_from, s.year
FROM series s
LEFT JOIN metadata_cache m ON m.provider = s.provider AND m.provider_id = s.provider_id
WHERE s.monitored = 1
  AND s.provider = ?
  AND (
      m.provider_id IS NULL
      OR m.fetched_at < CASE
             WHEN m.status IN ('FINISHED', 'CANCELLED') AND m.episode_count IS NOT NULL THEN ?
             ELSE ?
         END
  )
ORDER BY m.fetched_at IS NOT NULL, m.fetched_at
LIMIT ?
`

type ListTitlesDueMetadataRefreshParams struct {
	Provider    sql.NullString `json:"provider"`
	FetchedAt   string         `json:"fetched_at"`
	FetchedAt_2 string         `json:"fetched_at_2"`
	Limit       int64          `json:"limit"`
}

// Monitored series whose cached title snapshot is missing or stale under the
// status-aware TTL policy. Only a finished title with a known episode count
// earns the long cutoff; anything moving, unknown, or empty rides the short
// one, mirroring the freshness rule in metadata.Cached. Never-fetched series
// sort first; the limit bounds how much of the request budget one pass burns.
// Scoped to one provider for the same reason ListTitlesDueAiringSync is.
func (q *Queries) ListTitlesDueMetadataRefresh(ctx context.Context, arg ListTitlesDueMetadataRefreshParams) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, listTitlesDueMetadataRefresh,
		arg.Provider,
		arg.FetchedAt,
		arg.FetchedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderID,
			&i.Title,
			&i.Format,
			&i.Monitored,
			&i.CreatedAt,
			&i.QualityProfileID,
			&i.AiringSyncedAt,
			&i.PinnedGroup,
			&i.LastSearchedAt,
			&i.SearchBackoff,
			&i.NextSearchAt,
			&i.PinDelayHours,
			&i.SearchEpoch,
			&i.MonitorNewFrom,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTitlesWithProgress = `-- name: ListTitlesWithProgress :many
SELECT
    s.id, s.provider, s.provider_id, s.title, s.format, s.monitored, s.created_at, s.quality_profile_id, s.airing_synced_at, s.pinned_group, s.last_searched_at, s.search_backoff, s.next_search_at, s.pin_delay_hours, s.search_epoch, s.monitor_new_from, s.year,
    COUNT(w.id)                            AS total_items,
    CAST(COALESCE(SUM(w.monitored = 1), 0) AS INTEGER) AS monitored_items,
    CAST(COALESCE(SUM(
        w.monitored = 1 AND (w.kind = 'movie' OR w.airs_at IS NULL OR w.airs_at <= ?)
    ), 0) AS INTEGER)                      AS tracked_items,
    CAST(COALESCE(SUM(
        w.in_library = 1 AND w.monitored = 1 AND (w.kind = 'movie' OR w.airs_at IS NULL OR w.airs_at <= ?)
    ), 0) AS INTEGER)                      AS in_library_items
FROM series s
LEFT JOIN wanted_items w ON w.series_id = s.id
GROUP BY s.id
ORDER BY s.title
`

type ListTitlesWithProgressParams struct {
	AirsAt   sql.NullString `json:"airs_at"`
	AirsAt_2 sql.NullString `json:"airs_at_2"`
}

type ListTitlesWithProgressRow struct {
	ID               int64          `json:"id"`
	Provider         sql.NullString `json:"provider"`
	ProviderID       sql.NullInt64  `json:"provider_id"`
	Title            string         `json:"title"`
	Format           string         `json:"format"`
	Monitored        int64          `json:"monitored"`
	CreatedAt        string         `json:"created_at"`
	QualityProfileID int64          `json:"quality_profile_id"`
	AiringSyncedAt   sql.NullString `json:"airing_synced_at"`
	PinnedGroup      sql.NullString `json:"pinned_group"`
	LastSearchedAt   sql.NullString `json:"last_searched_at"`
	SearchBackoff    int64          `json:"search_backoff"`
	NextSearchAt     sql.NullString `json:"next_search_at"`
	PinDelayHours    sql.NullInt64  `json:"pin_delay_hours"`
	SearchEpoch      int64          `json:"search_epoch"`
	MonitorNewFrom   sql.NullInt64  `json:"monitor_new_from"`
	Year             int64          `json:"year"`
	TotalItems       int64          `json:"total_items"`
	MonitoredItems   int64          `json:"monitored_items"`
	TrackedItems     int64          `json:"tracked_items"`
	InLibraryItems   int64          `json:"in_library_items"`
}

// Progress is measured against what is being pursued (#188): monitored and
// already broadcast, numerator and denominator carrying the identical filter so
// a held unaired item cannot push a series past its own total. A null air date
// reads as aired, as everywhere else here, and so does a movie: its date is the
// theatrical premiere rather than the moment it becomes acquirable, so an
// announced film is being waited on now and must not read "Nothing aired yet"
// from the day it gains one. monitored_items rides along so a zero
// denominator can name its own cause: nothing aired yet, or nothing monitored.
// NOTE: keep comments here ASCII-only. sqlc's sqlite codegen miscounts byte vs.
// rune offsets and silently truncates the emitted SQL on a multi-byte character.
func (q *Queries) ListTitlesWithProgress(ctx context.Context, arg ListTitlesWithProgressParams) ([]ListTitlesWithProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listTitlesWithProgress, arg.AirsAt, arg.AirsAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTitlesWithProgressRow{}
	for rows.Next() {
		var i ListTitlesWithProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderID,
			&i.Title,
			&i.Format,
			&i.Monitored,
			&i.CreatedAt,
			&i.QualityProfileID,
			&i.AiringSyncedAt,
			&i.PinnedGroup,
			&i.LastSearchedAt,
			&i.SearchBackoff,
			&i.NextSearchAt,
			&i.PinDelayHours,
			&i.SearchEpoch,
			&i.MonitorNewFrom,
			&i.Year,
			&i.TotalItems,
			&i.MonitoredItems,
			&i.TrackedItems,
			&i.InLibraryItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackedNextAiring = `-- name: ListTrackedNextAiring :many
SELECT
    s.id,
    s.provider_id,
    s.airing_synced_at,
    w.number AS next_number,
    w.airs_at AS next_airs_at
FROM series s
LEFT JOIN wanted_items w ON w.id = (
    SELECT w2.id
    FROM wanted_items w2
    WHERE w2.series_id = s.id
      AND w2.airs_at IS NOT NULL
      AND w2.airs_at > ?
    ORDER BY w2.airs_at
    LIMIT 1
)
WHERE s.provider = ?
`

type ListTrackedNextAiringParams struct {
	AirsAt   sql.NullString `json:"airs_at"`
	Provider sql.NullString `json:"provider"`
}

type ListTrackedNextAiringRow struct {
	ID             int64          `json:"id"`
	ProviderID     sql.NullInt64  `json:"provider_id"`
	AiringSyncedAt sql.NullString `json:"airing_synced_at"`
	NextNumber     sql.NullInt64  `json:"next_number"`
	NextAirsAt     sql.NullString `json:"next_airs_at"`
}

// Discovery overlay rows: every series keyed on the given provider, joined to
// its next item scheduled after the given instant. airing_synced_at rides along
// so the caller can tell "synced, nothing upcoming" from "never synced".
func (q *Queries) ListTrackedNextAiring(ctx context.Context, arg ListTrackedNextAiringParams) ([]ListTrackedNextAiringRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrackedNextAiring, arg.AirsAt, arg.Provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackedNextAiringRow{}
	for rows.Next() {
		var i ListTrackedNextAiringRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.AiringSyncedAt,
			&i.NextNumber,
			&i.NextAirsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTitleAiringSyncedAt = `-- name: SetTitleAiringSyncedAt :exec
UPDATE series SET airing_synced_at = datetime('now')
WHERE id = ? AND airing_synced_at IS ?
`

type SetTitleAiringSyncedAtParams struct {
	ID             int64          `json:"id"`
	AiringSyncedAt sql.NullString `json:"airing_synced_at"`
}

// Guarded on the value read at selection: a refresh that cleared the stamp
// mid-sync must win, so the next airing pass re-pages the grown series.
func (q *Queries) SetTitleAiringSyncedAt(ctx context.Context, arg SetTitleAiringSyncedAtParams) error {
	_, err := q.db.ExecContext(ctx, setTitleAiringSyncedAt, arg.ID, arg.AiringSyncedAt)
	return err
}

const setTitleMonitorNewFrom = `-- name: SetTitleMonitorNewFrom :exec
UPDATE series SET monitor_new_from = ? WHERE id = ?
`

type SetTitleMonitorNewFromParams struct {
	MonitorNewFrom sql.NullInt64 `json:"monitor_new_from"`
	ID             int64         `json:"id"`
}

// The cut every later create site reads: an item numbered at or above it is
// created monitored. NULL monitors nothing new, and no mode writes one -- with
// nothing able to edit the cut afterwards, a null would be permanent.
func (q *Queries) SetTitleMonitorNewFrom(ctx context.Context, arg SetTitleMonitorNewFromParams) error {
	_, err := q.db.ExecContext(ctx, setTitleMonitorNewFrom, arg.MonitorNewFrom, arg.ID)
	return err
}

const setTitleMonitored = `-- name: SetTitleMonitored :exec
UPDATE series SET monitored = ? WHERE id = ?
`

type SetTitleMonitoredParams struct {
	Monitored int64 `json:"monitored"`
	ID        int64 `json:"id"`
}

func (q *Queries) SetTitleMonitored(ctx context.Context, arg SetTitleMonitoredParams) error {
	_, err := q.db.ExecContext(ctx, setTitleMonitored, arg.Monitored, arg.ID)
	return err
}

const setTitlePinnedGroup = `-- name: SetTitlePinnedGroup :execrows
UPDATE series SET pinned_group = ?, pin_delay_hours = ? WHERE id = ?
`

type SetTitlePinnedGroupParams struct {
	PinnedGroup   sql.NullString `json:"pinned_group"`
	PinDelayHours sql.NullInt64  `json:"pin_delay_hours"`
	ID            int64          `json:"id"`
}

// NULL clears the pin; execrows lets the handler 404 an unknown series. The
// delay rides along because it is meaningless without a group to wait for, so
// PUT-replacing one must replace the other.
func (q *Queries) SetTitlePinnedGroup(ctx context.Context, arg SetTitlePinnedGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTitlePinnedGroup, arg.PinnedGroup, arg.PinDelayHours, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTitleYear = `-- name: SetTitleYear :exec
UPDATE series SET year = ? WHERE id = ? AND ? > 0
`

type SetTitleYearParams struct {
	Year    int64       `json:"year"`
	ID      int64       `json:"id"`
	Column3 interface{} `json:"column_3"`
}

// Guarded in SQL so no future caller can bypass it: a transient upstream null
// must never erase a stored year, which the naming layer reads and where zero
// means "not on record".
func (q *Queries) SetTitleYear(ctx context.Context, arg SetTitleYearParams) error {
	_, err := q.db.ExecContext(ctx, setTitleYear, arg.Year, arg.ID, arg.Column3)
	return err
}
