// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wanted_search.sql

package db

import (
	"context"
	"database/sql"
)

const listSeriesDueWantedSearch = `-- name: ListSeriesDueWantedSearch :many
SELECT s.id, s.anilist_id, s.title, s.format, s.monitored, s.created_at, s.quality_profile_id, s.airing_synced_at, s.pinned_group, s.last_searched_at, s.search_backoff, s.next_search_at, s.pin_delay_hours, s.search_epoch
FROM series s
WHERE s.monitored = 1
  AND (s.next_search_at IS NULL OR s.next_search_at <= ?)
  AND EXISTS (
      SELECT 1
      FROM wanted_items w
      LEFT JOIN grabs g ON g.wanted_item_id = w.id
      WHERE w.series_id = s.id
        AND w.have = 0
        AND (g.wanted_item_id IS NULL OR g.status = 'failed')
        AND (w.airs_at IS NULL OR w.airs_at <= ?)
  )
ORDER BY s.next_search_at IS NOT NULL, s.next_search_at
LIMIT ?
`

type ListSeriesDueWantedSearchParams struct {
	NextSearchAt sql.NullString `json:"next_search_at"`
	AirsAt       sql.NullString `json:"airs_at"`
	Limit        int64          `json:"limit"`
}

// Monitored series with something actually searchable right now: an item still
// wanted (never grabbed, or a grab that failed) whose broadcast has happened or
// was never published. Air dates are nullable by design, so a missing one must
// read as searchable rather than as "not yet". Series never searched sort first;
// the limit bounds how much of the indexer budget one pass can burn.
// NOTE: keep comments here ASCII-only. sqlc's sqlite codegen miscounts byte vs.
// rune offsets and silently truncates the emitted SQL on a multi-byte character.
func (q *Queries) ListSeriesDueWantedSearch(ctx context.Context, arg ListSeriesDueWantedSearchParams) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesDueWantedSearch, arg.NextSearchAt, arg.AirsAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.AnilistID,
			&i.Title,
			&i.Format,
			&i.Monitored,
			&i.CreatedAt,
			&i.QualityProfileID,
			&i.AiringSyncedAt,
			&i.PinnedGroup,
			&i.LastSearchedAt,
			&i.SearchBackoff,
			&i.NextSearchAt,
			&i.PinDelayHours,
			&i.SearchEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesWithWantedItems = `-- name: ListSeriesWithWantedItems :many
SELECT s.id, s.anilist_id, s.title, s.format, s.monitored, s.created_at, s.quality_profile_id, s.airing_synced_at, s.pinned_group, s.last_searched_at, s.search_backoff, s.next_search_at, s.pin_delay_hours, s.search_epoch
FROM series s
WHERE s.monitored = 1
  AND EXISTS (
      SELECT 1
      FROM wanted_items w
      LEFT JOIN grabs g ON g.wanted_item_id = w.id
      WHERE w.series_id = s.id
        AND w.have = 0
        AND (g.wanted_item_id IS NULL OR g.status = 'failed')
        AND (w.airs_at IS NULL OR w.airs_at <= ?)
  )
ORDER BY s.id
`

// Monitored series with something worth grabbing right now, ignoring search
// cadence. The feed poll issues no indexer request per series -- one request
// answers for every series at once -- so the budget the sweep's LIMIT protects
// does not apply here. The wanted predicate is deliberately the sweep's,
// character for character, so both entry points agree on what is grabbable.
// NOTE: keep comments here ASCII-only. sqlc's sqlite codegen miscounts byte vs.
// rune offsets and silently truncates the emitted SQL on a multi-byte character.
func (q *Queries) ListSeriesWithWantedItems(ctx context.Context, airsAt sql.NullString) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesWithWantedItems, airsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.AnilistID,
			&i.Title,
			&i.Format,
			&i.Monitored,
			&i.CreatedAt,
			&i.QualityProfileID,
			&i.AiringSyncedAt,
			&i.PinnedGroup,
			&i.LastSearchedAt,
			&i.SearchBackoff,
			&i.NextSearchAt,
			&i.PinDelayHours,
			&i.SearchEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWantedItemsWithGrabState = `-- name: ListWantedItemsWithGrabState :many
SELECT w.id, w.series_id, w.kind, w.number, w.title, w.have, w.airs_at, g.status AS grab_status
FROM wanted_items w
LEFT JOIN grabs g ON g.wanted_item_id = w.id
WHERE w.series_id = ?
ORDER BY w.number
`

type ListWantedItemsWithGrabStateRow struct {
	ID         int64          `json:"id"`
	SeriesID   int64          `json:"series_id"`
	Kind       string         `json:"kind"`
	Number     sql.NullInt64  `json:"number"`
	Title      sql.NullString `json:"title"`
	Have       int64          `json:"have"`
	AirsAt     sql.NullString `json:"airs_at"`
	GrabStatus sql.NullString `json:"grab_status"`
}

// One grab per item (UNIQUE) keeps the join 1:1, so the sweep can tell an
// in-flight episode from a wanted one in a single query per series.
func (q *Queries) ListWantedItemsWithGrabState(ctx context.Context, seriesID int64) ([]ListWantedItemsWithGrabStateRow, error) {
	rows, err := q.db.QueryContext(ctx, listWantedItemsWithGrabState, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWantedItemsWithGrabStateRow{}
	for rows.Next() {
		var i ListWantedItemsWithGrabStateRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Kind,
			&i.Number,
			&i.Title,
			&i.Have,
			&i.AirsAt,
			&i.GrabStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetSeriesSearchState = `-- name: ResetSeriesSearchState :exec
UPDATE series
SET search_backoff = 0, next_search_at = NULL, search_epoch = search_epoch + 1
WHERE id = ?
`

// Puts a series back at the front of the queue: due now, no accumulated backoff.
// Bumping the epoch is what makes an in-flight sweep's write lose.
func (q *Queries) ResetSeriesSearchState(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetSeriesSearchState, id)
	return err
}

const setSeriesSearchState = `-- name: SetSeriesSearchState :execrows
UPDATE series
SET last_searched_at = ?, search_backoff = ?, next_search_at = ?
WHERE id = ? AND search_epoch = ?
`

type SetSeriesSearchStateParams struct {
	LastSearchedAt sql.NullString `json:"last_searched_at"`
	SearchBackoff  int64          `json:"search_backoff"`
	NextSearchAt   sql.NullString `json:"next_search_at"`
	ID             int64          `json:"id"`
	SearchEpoch    int64          `json:"search_epoch"`
}

// Guarded on the epoch read at selection: a reset that landed mid-sweep (the
// series grew, was re-monitored, or was repinned) must win over the backoff
// computed against the stale state. Guarding on next_search_at could not do
// that -- a reset writes NULL, which is also what a due series usually already
// held. execrows is what lets the caller see that its write lost.
func (q *Queries) SetSeriesSearchState(ctx context.Context, arg SetSeriesSearchStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSeriesSearchState,
		arg.LastSearchedAt,
		arg.SearchBackoff,
		arg.NextSearchAt,
		arg.ID,
		arg.SearchEpoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
