// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wanted_items.sql

package db

import (
	"context"
	"database/sql"
)

const createWantedItem = `-- name: CreateWantedItem :one
INSERT INTO wanted_items (series_id, kind, number, title, have)
VALUES (?, ?, ?, ?, ?)
RETURNING id, series_id, kind, number, title, have, airs_at
`

type CreateWantedItemParams struct {
	SeriesID int64          `json:"series_id"`
	Kind     string         `json:"kind"`
	Number   sql.NullInt64  `json:"number"`
	Title    sql.NullString `json:"title"`
	Have     int64          `json:"have"`
}

func (q *Queries) CreateWantedItem(ctx context.Context, arg CreateWantedItemParams) (WantedItem, error) {
	row := q.db.QueryRowContext(ctx, createWantedItem,
		arg.SeriesID,
		arg.Kind,
		arg.Number,
		arg.Title,
		arg.Have,
	)
	var i WantedItem
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Kind,
		&i.Number,
		&i.Title,
		&i.Have,
		&i.AirsAt,
	)
	return i, err
}

const listWantedItems = `-- name: ListWantedItems :many
SELECT id, series_id, kind, number, title, have, airs_at
FROM wanted_items
WHERE series_id = ?
ORDER BY number
`

func (q *Queries) ListWantedItems(ctx context.Context, seriesID int64) ([]WantedItem, error) {
	rows, err := q.db.QueryContext(ctx, listWantedItems, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WantedItem{}
	for rows.Next() {
		var i WantedItem
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Kind,
			&i.Number,
			&i.Title,
			&i.Have,
			&i.AirsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWantedItemHave = `-- name: SetWantedItemHave :exec
UPDATE wanted_items SET have = ? WHERE id = ?
`

type SetWantedItemHaveParams struct {
	Have int64 `json:"have"`
	ID   int64 `json:"id"`
}

func (q *Queries) SetWantedItemHave(ctx context.Context, arg SetWantedItemHaveParams) error {
	_, err := q.db.ExecContext(ctx, setWantedItemHave, arg.Have, arg.ID)
	return err
}

const upsertWantedItem = `-- name: UpsertWantedItem :execrows
INSERT INTO wanted_items (series_id, kind, number, title, have)
VALUES (?, ?, ?, ?, 0)
ON CONFLICT (series_id, kind, number) DO NOTHING
`

type UpsertWantedItemParams struct {
	SeriesID int64          `json:"series_id"`
	Kind     string         `json:"kind"`
	Number   sql.NullInt64  `json:"number"`
	Title    sql.NullString `json:"title"`
}

// DO NOTHING keeps refresh from ever clobbering an existing item's have or
// title; the row count tells the caller whether the series actually grew.
func (q *Queries) UpsertWantedItem(ctx context.Context, arg UpsertWantedItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertWantedItem,
		arg.SeriesID,
		arg.Kind,
		arg.Number,
		arg.Title,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertWantedItemAiring = `-- name: UpsertWantedItemAiring :exec
INSERT INTO wanted_items (series_id, kind, number, airs_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (series_id, kind, number) DO UPDATE SET airs_at = excluded.airs_at
`

type UpsertWantedItemAiringParams struct {
	SeriesID int64          `json:"series_id"`
	Kind     string         `json:"kind"`
	Number   sql.NullInt64  `json:"number"`
	AirsAt   sql.NullString `json:"airs_at"`
}

// Creating the item matters for a null-count long-runner: the schedule is the
// only source that knows its episodes exist. Only airs_at moves on conflict.
func (q *Queries) UpsertWantedItemAiring(ctx context.Context, arg UpsertWantedItemAiringParams) error {
	_, err := q.db.ExecContext(ctx, upsertWantedItemAiring,
		arg.SeriesID,
		arg.Kind,
		arg.Number,
		arg.AirsAt,
	)
	return err
}
