// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wanted_queue.sql

package db

import (
	"context"
	"database/sql"
)

const listActiveBlocklistCounts = `-- name: ListActiveBlocklistCounts :many
SELECT series_id, COUNT(*) AS entries
FROM release_blocklist
WHERE blocked_until IS NULL OR blocked_until > ?
GROUP BY series_id
`

type ListActiveBlocklistCountsRow struct {
	SeriesID int64 `json:"series_id"`
	Entries  int64 `json:"entries"`
}

// How many releases each series is currently refusing, for the reason column.
// Per series rather than per item because that is the blocklist's own scope.
// A NULL blocked_until is permanent.
func (q *Queries) ListActiveBlocklistCounts(ctx context.Context, blockedUntil sql.NullString) ([]ListActiveBlocklistCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBlocklistCounts, blockedUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveBlocklistCountsRow{}
	for rows.Next() {
		var i ListActiveBlocklistCountsRow
		if err := rows.Scan(&i.SeriesID, &i.Entries); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCutoffUnmetPage = `-- name: ListCutoffUnmetPage :many
SELECT w.id, w.series_id, w.kind, w.number, w.title, w.have, w.airs_at, w.held_release_title,
       s.title         AS series_title,
       s.monitored     AS series_monitored,
       qp.id           AS profile_id,
       qp.name         AS profile_name,
       qp.cutoff_score AS profile_cutoff_score,
       g.status        AS grab_status,
       g.release_title AS grab_release_title,
       g.last_error    AS grab_last_error
FROM wanted_items w
JOIN series s ON s.id = w.series_id
JOIN quality_profiles qp ON qp.id = s.quality_profile_id
LEFT JOIN grabs g ON g.wanted_item_id = w.id
WHERE w.have = 1
  AND w.held_release_title != ''
  AND qp.upgrades_enabled = 1
  AND (? = 1 OR s.monitored = 1)
  AND (COALESCE(w.airs_at, '') < ? OR (COALESCE(w.airs_at, '') = ? AND w.id > ?))
ORDER BY COALESCE(w.airs_at, '') DESC, w.id
LIMIT ?
`

type ListCutoffUnmetPageParams struct {
	Column1  interface{}    `json:"column_1"`
	AirsAt   sql.NullString `json:"airs_at"`
	AirsAt_2 sql.NullString `json:"airs_at_2"`
	ID       int64          `json:"id"`
	Limit    int64          `json:"limit"`
}

type ListCutoffUnmetPageRow struct {
	ID                 int64          `json:"id"`
	SeriesID           int64          `json:"series_id"`
	Kind               string         `json:"kind"`
	Number             sql.NullInt64  `json:"number"`
	Title              sql.NullString `json:"title"`
	Have               int64          `json:"have"`
	AirsAt             sql.NullString `json:"airs_at"`
	HeldReleaseTitle   string         `json:"held_release_title"`
	SeriesTitle        string         `json:"series_title"`
	SeriesMonitored    int64          `json:"series_monitored"`
	ProfileID          int64          `json:"profile_id"`
	ProfileName        string         `json:"profile_name"`
	ProfileCutoffScore int64          `json:"profile_cutoff_score"`
	GrabStatus         sql.NullString `json:"grab_status"`
	GrabReleaseTitle   sql.NullString `json:"grab_release_title"`
	GrabLastError      sql.NullString `json:"grab_last_error"`
}

// Held items on an upgrading profile: the candidate set for Cutoff Unmet, whose
// membership test (does the held release score below the profile cutoff?) needs
// the parser and so is settled in Go. Opt-in is per profile, so a series on a
// non-upgrading profile never appears. held_release_title is the scoring input,
// and an item without one has nothing to rate. Ordering and cursor match
// ListMissingItemsPage.
func (q *Queries) ListCutoffUnmetPage(ctx context.Context, arg ListCutoffUnmetPageParams) ([]ListCutoffUnmetPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listCutoffUnmetPage,
		arg.Column1,
		arg.AirsAt,
		arg.AirsAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCutoffUnmetPageRow{}
	for rows.Next() {
		var i ListCutoffUnmetPageRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Kind,
			&i.Number,
			&i.Title,
			&i.Have,
			&i.AirsAt,
			&i.HeldReleaseTitle,
			&i.SeriesTitle,
			&i.SeriesMonitored,
			&i.ProfileID,
			&i.ProfileName,
			&i.ProfileCutoffScore,
			&i.GrabStatus,
			&i.GrabReleaseTitle,
			&i.GrabLastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissingItemsPage = `-- name: ListMissingItemsPage :many

SELECT w.id, w.series_id, w.kind, w.number, w.title, w.have, w.airs_at, w.held_release_title,
       s.title            AS series_title,
       s.monitored        AS series_monitored,
       s.last_searched_at AS series_last_searched_at,
       s.next_search_at   AS series_next_search_at,
       g.status           AS grab_status,
       g.release_title    AS grab_release_title,
       g.last_error       AS grab_last_error
FROM wanted_items w
JOIN series s ON s.id = w.series_id
LEFT JOIN grabs g ON g.wanted_item_id = w.id
WHERE w.have = 0
  AND (g.wanted_item_id IS NULL OR g.status = 'failed')
  AND (? = 1 OR s.monitored = 1)
  AND (? = 1 OR w.airs_at IS NULL OR w.airs_at <= ?)
  AND (COALESCE(w.airs_at, '') < ? OR (COALESCE(w.airs_at, '') = ? AND w.id > ?))
ORDER BY COALESCE(w.airs_at, '') DESC, w.id
LIMIT ?
`

type ListMissingItemsPageParams struct {
	Column1  interface{}    `json:"column_1"`
	Column2  interface{}    `json:"column_2"`
	AirsAt   sql.NullString `json:"airs_at"`
	AirsAt_2 sql.NullString `json:"airs_at_2"`
	AirsAt_3 sql.NullString `json:"airs_at_3"`
	ID       int64          `json:"id"`
	Limit    int64          `json:"limit"`
}

type ListMissingItemsPageRow struct {
	ID                   int64          `json:"id"`
	SeriesID             int64          `json:"series_id"`
	Kind                 string         `json:"kind"`
	Number               sql.NullInt64  `json:"number"`
	Title                sql.NullString `json:"title"`
	Have                 int64          `json:"have"`
	AirsAt               sql.NullString `json:"airs_at"`
	HeldReleaseTitle     string         `json:"held_release_title"`
	SeriesTitle          string         `json:"series_title"`
	SeriesMonitored      int64          `json:"series_monitored"`
	SeriesLastSearchedAt sql.NullString `json:"series_last_searched_at"`
	SeriesNextSearchAt   sql.NullString `json:"series_next_search_at"`
	GrabStatus           sql.NullString `json:"grab_status"`
	GrabReleaseTitle     sql.NullString `json:"grab_release_title"`
	GrabLastError        sql.NullString `json:"grab_last_error"`
}

// The cross-series wanted queue (issue #150): Missing and Cutoff Unmet, both
// keyset-paginated. A missing set is unbounded -- a fresh library add can put
// hundreds of items in it at once -- so neither list may load whole.
// NOTE: keep comments in this file ASCII-only. sqlc's sqlite codegen miscounts
// byte vs. rune offsets and silently truncates the emitted SQL on a multi-byte
// character. See CLAUDE.md.
// Every item still worth acquiring, across all series. The wanted half is the
// sweep's predicate character for character (the EXISTS body of
// ListSeriesDueWantedSearch), which is what keeps this page honest about what
// automation will go after; an in-flight grab is absent by construction, being
// Activity's to show. The cadence columns ride along because the reason column
// is derived from stored state alone.
// Ordered newest broadcast first, undated last: COALESCE sorts a null air date
// below every timestamp, and lexicographic compare on the one stored layout is
// chronological. Id ascends inside a group deliberately -- a series with no
// schedule at all is a back catalogue, and draining one reads forwards, not
// backwards. The cursor pair is that same (air date, id), so a first page passes
// a sentinel above every stored value and one query serves every page.
func (q *Queries) ListMissingItemsPage(ctx context.Context, arg ListMissingItemsPageParams) ([]ListMissingItemsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listMissingItemsPage,
		arg.Column1,
		arg.Column2,
		arg.AirsAt,
		arg.AirsAt_2,
		arg.AirsAt_3,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMissingItemsPageRow{}
	for rows.Next() {
		var i ListMissingItemsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Kind,
			&i.Number,
			&i.Title,
			&i.Have,
			&i.AirsAt,
			&i.HeldReleaseTitle,
			&i.SeriesTitle,
			&i.SeriesMonitored,
			&i.SeriesLastSearchedAt,
			&i.SeriesNextSearchAt,
			&i.GrabStatus,
			&i.GrabReleaseTitle,
			&i.GrabLastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
