// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wanted_queue.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const listActiveBlocklistCounts = `-- name: ListActiveBlocklistCounts :many
SELECT series_id, COUNT(*) AS entries
FROM release_blocklist
WHERE blocked_until IS NULL OR blocked_until > ?
GROUP BY series_id
`

type ListActiveBlocklistCountsRow struct {
	SeriesID int64 `json:"series_id"`
	Entries  int64 `json:"entries"`
}

// How many releases each series is currently refusing, for the reason column.
// Per series rather than per item because that is the blocklist's own scope.
// A NULL blocked_until is permanent.
func (q *Queries) ListActiveBlocklistCounts(ctx context.Context, blockedUntil sql.NullString) ([]ListActiveBlocklistCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBlocklistCounts, blockedUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveBlocklistCountsRow{}
	for rows.Next() {
		var i ListActiveBlocklistCountsRow
		if err := rows.Scan(&i.SeriesID, &i.Entries); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCutoffUnmetPage = `-- name: ListCutoffUnmetPage :many
SELECT w.id, w.series_id, w.kind, w.number, w.title, w.have, w.airs_at, w.held_release_title,
       s.title         AS series_title,
       s.monitored     AS series_monitored,
       qp.id           AS profile_id,
       qp.name         AS profile_name,
       qp.cutoff_score AS profile_cutoff_score,
       g.status        AS grab_status,
       g.release_title AS grab_release_title,
       g.last_error    AS grab_last_error
FROM wanted_items w
JOIN series s ON s.id = w.series_id
JOIN quality_profiles qp ON qp.id = s.quality_profile_id
LEFT JOIN grabs g ON g.wanted_item_id = w.id
WHERE w.have = 1
  AND w.held_release_title != ''
  AND qp.upgrades_enabled = 1
  AND (? = 1 OR s.monitored = 1)
  AND (COALESCE(w.airs_at, '') < ? OR (COALESCE(w.airs_at, '') = ? AND w.id > ?))
ORDER BY COALESCE(w.airs_at, '') DESC, w.id
LIMIT ?
`

type ListCutoffUnmetPageParams struct {
	Column1  interface{}    `json:"column_1"`
	AirsAt   sql.NullString `json:"airs_at"`
	AirsAt_2 sql.NullString `json:"airs_at_2"`
	ID       int64          `json:"id"`
	Limit    int64          `json:"limit"`
}

type ListCutoffUnmetPageRow struct {
	ID                 int64          `json:"id"`
	SeriesID           int64          `json:"series_id"`
	Kind               string         `json:"kind"`
	Number             sql.NullInt64  `json:"number"`
	Title              sql.NullString `json:"title"`
	Have               int64          `json:"have"`
	AirsAt             sql.NullString `json:"airs_at"`
	HeldReleaseTitle   string         `json:"held_release_title"`
	SeriesTitle        string         `json:"series_title"`
	SeriesMonitored    int64          `json:"series_monitored"`
	ProfileID          int64          `json:"profile_id"`
	ProfileName        string         `json:"profile_name"`
	ProfileCutoffScore int64          `json:"profile_cutoff_score"`
	GrabStatus         sql.NullString `json:"grab_status"`
	GrabReleaseTitle   sql.NullString `json:"grab_release_title"`
	GrabLastError      sql.NullString `json:"grab_last_error"`
}

// Held items on an upgrading profile: the candidate set for Cutoff Unmet, whose
// membership test (does the held release score below the profile cutoff?) needs
// the parser and so is settled in Go. Opt-in is per profile, so a series on a
// non-upgrading profile never appears. held_release_title is the scoring input,
// and an item without one has nothing to rate. Ordering and cursor match
// ListMissingItemsPage.
func (q *Queries) ListCutoffUnmetPage(ctx context.Context, arg ListCutoffUnmetPageParams) ([]ListCutoffUnmetPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listCutoffUnmetPage,
		arg.Column1,
		arg.AirsAt,
		arg.AirsAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCutoffUnmetPageRow{}
	for rows.Next() {
		var i ListCutoffUnmetPageRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Kind,
			&i.Number,
			&i.Title,
			&i.Have,
			&i.AirsAt,
			&i.HeldReleaseTitle,
			&i.SeriesTitle,
			&i.SeriesMonitored,
			&i.ProfileID,
			&i.ProfileName,
			&i.ProfileCutoffScore,
			&i.GrabStatus,
			&i.GrabReleaseTitle,
			&i.GrabLastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissingItemsBySeries = `-- name: ListMissingItemsBySeries :many
SELECT w.id, w.series_id, w.kind, w.number, w.title, w.have, w.airs_at, w.held_release_title,
       g.status        AS grab_status,
       g.release_title AS grab_release_title,
       g.last_error    AS grab_last_error
FROM wanted_items w
LEFT JOIN grabs g ON g.wanted_item_id = w.id
WHERE w.series_id IN (/*SLICE:series_ids*/?)
  AND w.have = 0
  AND (g.wanted_item_id IS NULL OR g.status = 'failed')
  AND (? = 1 OR w.airs_at IS NULL OR w.airs_at <= ?)
ORDER BY w.series_id, w.number
`

type ListMissingItemsBySeriesParams struct {
	SeriesIds []int64        `json:"series_ids"`
	Column2   interface{}    `json:"column_2"`
	AirsAt    sql.NullString `json:"airs_at"`
}

type ListMissingItemsBySeriesRow struct {
	ID               int64          `json:"id"`
	SeriesID         int64          `json:"series_id"`
	Kind             string         `json:"kind"`
	Number           sql.NullInt64  `json:"number"`
	Title            sql.NullString `json:"title"`
	Have             int64          `json:"have"`
	AirsAt           sql.NullString `json:"airs_at"`
	HeldReleaseTitle string         `json:"held_release_title"`
	GrabStatus       sql.NullString `json:"grab_status"`
	GrabReleaseTitle sql.NullString `json:"grab_release_title"`
	GrabLastError    sql.NullString `json:"grab_last_error"`
}

// The items behind one page of groups. Same wanted predicate and unaired filter
// as the series page, so a group and its items are computed from one reading of
// the world. Number ascends within a series deliberately: a back catalogue
// drains forwards, and episodes enumerate forwards however their dates fall.
func (q *Queries) ListMissingItemsBySeries(ctx context.Context, arg ListMissingItemsBySeriesParams) ([]ListMissingItemsBySeriesRow, error) {
	query := listMissingItemsBySeries
	var queryParams []interface{}
	if len(arg.SeriesIds) > 0 {
		for _, v := range arg.SeriesIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:series_ids*/?", strings.Repeat(",?", len(arg.SeriesIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:series_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Column2)
	queryParams = append(queryParams, arg.AirsAt)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMissingItemsBySeriesRow{}
	for rows.Next() {
		var i ListMissingItemsBySeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Kind,
			&i.Number,
			&i.Title,
			&i.Have,
			&i.AirsAt,
			&i.HeldReleaseTitle,
			&i.GrabStatus,
			&i.GrabReleaseTitle,
			&i.GrabLastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissingSeriesPage = `-- name: ListMissingSeriesPage :many

SELECT s.id, s.title, s.monitored, s.last_searched_at, s.next_search_at,
       MAX(COALESCE(w.airs_at, '')) AS latest_missing_air,
       COUNT(*)                     AS missing
FROM wanted_items w
JOIN series s ON s.id = w.series_id
LEFT JOIN grabs g ON g.wanted_item_id = w.id
WHERE w.have = 0
  AND (g.wanted_item_id IS NULL OR g.status = 'failed')
  AND (? = 1 OR s.monitored = 1)
  AND (? = 1 OR w.airs_at IS NULL OR w.airs_at <= ?)
GROUP BY s.id
HAVING MAX(COALESCE(w.airs_at, '')) < ? OR (MAX(COALESCE(w.airs_at, '')) = ? AND s.id > ?)
ORDER BY MAX(COALESCE(w.airs_at, '')) DESC, s.id
LIMIT ?
`

type ListMissingSeriesPageParams struct {
	Column1  interface{}    `json:"column_1"`
	Column2  interface{}    `json:"column_2"`
	AirsAt   sql.NullString `json:"airs_at"`
	AirsAt_2 sql.NullString `json:"airs_at_2"`
	AirsAt_3 sql.NullString `json:"airs_at_3"`
	ID       int64          `json:"id"`
	Limit    int64          `json:"limit"`
}

type ListMissingSeriesPageRow struct {
	ID               int64          `json:"id"`
	Title            string         `json:"title"`
	Monitored        int64          `json:"monitored"`
	LastSearchedAt   sql.NullString `json:"last_searched_at"`
	NextSearchAt     sql.NullString `json:"next_search_at"`
	LatestMissingAir interface{}    `json:"latest_missing_air"`
	Missing          int64          `json:"missing"`
}

// The cross-series wanted queue (issue #150): Missing and Cutoff Unmet, both
// keyset-paginated. A missing set is unbounded -- a fresh library add can put
// hundreds of items in it at once -- so neither list may load whole.
// NOTE: keep comments in this file ASCII-only. sqlc's sqlite codegen miscounts
// byte vs. rune offsets and silently truncates the emitted SQL on a multi-byte
// character. See CLAUDE.md.
// The Missing tab's pagination unit is the series, so a group can never split
// across a page boundary. The wanted half is the sweep's predicate character
// for character (the EXISTS body of ListSeriesDueWantedSearch), which is what
// keeps this page honest about what automation will go after; an in-flight
// grab is absent by construction, being Activity's to show. Groups are ordered
// newest missing broadcast first, all-undated series last: COALESCE sorts a
// null air date below every timestamp, and lexicographic compare on the one
// stored layout is chronological. The keyset lives in HAVING because it binds
// on the aggregate; a first page passes a sentinel above every stored value so
// one query serves every page. The count is the whole group even when the
// handler caps the items it returns for one.
func (q *Queries) ListMissingSeriesPage(ctx context.Context, arg ListMissingSeriesPageParams) ([]ListMissingSeriesPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listMissingSeriesPage,
		arg.Column1,
		arg.Column2,
		arg.AirsAt,
		arg.AirsAt_2,
		arg.AirsAt_3,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMissingSeriesPageRow{}
	for rows.Next() {
		var i ListMissingSeriesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Monitored,
			&i.LastSearchedAt,
			&i.NextSearchAt,
			&i.LatestMissingAir,
			&i.Missing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
