// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wanted_items.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createWantedItem = `-- name: CreateWantedItem :one
INSERT INTO wanted_items (series_id, kind, number, title, in_library, monitored)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, series_id, kind, number, title, in_library, airs_at, held_release_title, monitored
`

type CreateWantedItemParams struct {
	SeriesID  int64          `json:"series_id"`
	Kind      string         `json:"kind"`
	Number    sql.NullInt64  `json:"number"`
	Title     sql.NullString `json:"title"`
	InLibrary int64          `json:"in_library"`
	Monitored int64          `json:"monitored"`
}

func (q *Queries) CreateWantedItem(ctx context.Context, arg CreateWantedItemParams) (WantedItem, error) {
	row := q.db.QueryRowContext(ctx, createWantedItem,
		arg.SeriesID,
		arg.Kind,
		arg.Number,
		arg.Title,
		arg.InLibrary,
		arg.Monitored,
	)
	var i WantedItem
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Kind,
		&i.Number,
		&i.Title,
		&i.InLibrary,
		&i.AirsAt,
		&i.HeldReleaseTitle,
		&i.Monitored,
	)
	return i, err
}

const getWantedItemByNumber = `-- name: GetWantedItemByNumber :one
SELECT w.id, w.series_id, w.kind, w.number, w.title, w.in_library, w.airs_at, w.held_release_title, w.monitored, g.status AS grab_status
FROM wanted_items w
LEFT JOIN grabs g ON g.wanted_item_id = w.id
WHERE w.series_id = ? AND w.kind = ? AND w.number = ?
`

type GetWantedItemByNumberParams struct {
	SeriesID int64         `json:"series_id"`
	Kind     string        `json:"kind"`
	Number   sql.NullInt64 `json:"number"`
}

type GetWantedItemByNumberRow struct {
	ID               int64          `json:"id"`
	SeriesID         int64          `json:"series_id"`
	Kind             string         `json:"kind"`
	Number           sql.NullInt64  `json:"number"`
	Title            sql.NullString `json:"title"`
	InLibrary        int64          `json:"in_library"`
	AirsAt           sql.NullString `json:"airs_at"`
	HeldReleaseTitle string         `json:"held_release_title"`
	Monitored        int64          `json:"monitored"`
	GrabStatus       sql.NullString `json:"grab_status"`
}

// One read answers exists / had / already spoken for, which is the whole guard
// on placing a payload file for an item no grab row claimed. UNIQUE
// (wanted_item_id) on grabs keeps the join 1:1.
func (q *Queries) GetWantedItemByNumber(ctx context.Context, arg GetWantedItemByNumberParams) (GetWantedItemByNumberRow, error) {
	row := q.db.QueryRowContext(ctx, getWantedItemByNumber, arg.SeriesID, arg.Kind, arg.Number)
	var i GetWantedItemByNumberRow
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Kind,
		&i.Number,
		&i.Title,
		&i.InLibrary,
		&i.AirsAt,
		&i.HeldReleaseTitle,
		&i.Monitored,
		&i.GrabStatus,
	)
	return i, err
}

const listCalendarItems = `-- name: ListCalendarItems :many
SELECT w.id, w.series_id, w.kind, w.number, w.title, w.in_library, w.airs_at, w.held_release_title, w.monitored,
       s.title         AS title_name,
       s.format        AS title_format,
       s.monitored     AS title_monitored,
       g.status        AS grab_status,
       g.release_title AS grab_release_title,
       g.last_error    AS grab_last_error
FROM wanted_items w
JOIN series s ON s.id = w.series_id
LEFT JOIN grabs g ON g.wanted_item_id = w.id
WHERE w.airs_at IS NOT NULL AND w.airs_at >= ? AND w.airs_at < ?
ORDER BY w.airs_at, s.title, w.number
`

type ListCalendarItemsParams struct {
	AirsAt   sql.NullString `json:"airs_at"`
	AirsAt_2 sql.NullString `json:"airs_at_2"`
}

type ListCalendarItemsRow struct {
	ID               int64          `json:"id"`
	SeriesID         int64          `json:"series_id"`
	Kind             string         `json:"kind"`
	Number           sql.NullInt64  `json:"number"`
	Title            sql.NullString `json:"title"`
	InLibrary        int64          `json:"in_library"`
	AirsAt           sql.NullString `json:"airs_at"`
	HeldReleaseTitle string         `json:"held_release_title"`
	Monitored        int64          `json:"monitored"`
	TitleName        string         `json:"title_name"`
	TitleFormat      string         `json:"title_format"`
	TitleMonitored   int64          `json:"title_monitored"`
	GrabStatus       sql.NullString `json:"grab_status"`
	GrabReleaseTitle sql.NullString `json:"grab_release_title"`
	GrabLastError    sql.NullString `json:"grab_last_error"`
}

// Stored timestamps are UTC in one fixed layout, so lexicographic range
// compare is chronological. One grab per item (UNIQUE) keeps the join 1:1.
func (q *Queries) ListCalendarItems(ctx context.Context, arg ListCalendarItemsParams) ([]ListCalendarItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCalendarItems, arg.AirsAt, arg.AirsAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCalendarItemsRow{}
	for rows.Next() {
		var i ListCalendarItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Kind,
			&i.Number,
			&i.Title,
			&i.InLibrary,
			&i.AirsAt,
			&i.HeldReleaseTitle,
			&i.Monitored,
			&i.TitleName,
			&i.TitleFormat,
			&i.TitleMonitored,
			&i.GrabStatus,
			&i.GrabReleaseTitle,
			&i.GrabLastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTitleIDsForUnmonitoredItems = `-- name: ListTitleIDsForUnmonitoredItems :many
SELECT DISTINCT series_id
FROM wanted_items
WHERE id IN (/*SLICE:ids*/?) AND monitored = 0
`

// The series a re-monitor will actually change, so the cadence reset lands once
// per series and only where something moved. Read before the update, in the
// same transaction, since the update reports only a row count.
func (q *Queries) ListTitleIDsForUnmonitoredItems(ctx context.Context, ids []int64) ([]int64, error) {
	query := listTitleIDsForUnmonitoredItems
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var series_id int64
		if err := rows.Scan(&series_id); err != nil {
			return nil, err
		}
		items = append(items, series_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnscheduledTitles = `-- name: ListUnscheduledTitles :many
SELECT DISTINCT s.id, s.title, s.airing_synced_at IS NOT NULL AS schedule_checked
FROM series s
JOIN wanted_items w ON w.series_id = s.id
WHERE (? = 1 OR s.monitored = 1) AND w.in_library = 0 AND w.airs_at IS NULL
ORDER BY s.title
`

type ListUnscheduledTitlesRow struct {
	ID              int64  `json:"id"`
	Title           string `json:"title"`
	ScheduleChecked bool   `json:"schedule_checked"`
}

// Series still missing an episode the provider gives no air date for, so the
// calendar can surface them instead of silently omitting them. The first param
// mirrors the grid's own unmonitored filter: a footer explaining an absence
// must cover exactly the population the grid was asked to show (#183).
// schedule_checked separates the two absences the footer would otherwise assert
// as one: nothing writes airs_at but the airing sync, so an unstamped title is
// one we have not asked about rather than one the provider publishes nothing for.
func (q *Queries) ListUnscheduledTitles(ctx context.Context, dollar_1 interface{}) ([]ListUnscheduledTitlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnscheduledTitles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnscheduledTitlesRow{}
	for rows.Next() {
		var i ListUnscheduledTitlesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.ScheduleChecked); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWantedItems = `-- name: ListWantedItems :many
SELECT id, series_id, kind, number, title, in_library, airs_at, held_release_title, monitored
FROM wanted_items
WHERE series_id = ?
ORDER BY number
`

func (q *Queries) ListWantedItems(ctx context.Context, seriesID int64) ([]WantedItem, error) {
	rows, err := q.db.QueryContext(ctx, listWantedItems, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WantedItem{}
	for rows.Next() {
		var i WantedItem
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Kind,
			&i.Number,
			&i.Title,
			&i.InLibrary,
			&i.AirsAt,
			&i.HeldReleaseTitle,
			&i.Monitored,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWantedItemAirsAtIfNull = `-- name: SetWantedItemAirsAtIfNull :exec
UPDATE wanted_items
SET airs_at = ?
WHERE series_id = ? AND kind = ? AND number = ? AND airs_at IS NULL
`

type SetWantedItemAirsAtIfNullParams struct {
	AirsAt   sql.NullString `json:"airs_at"`
	SeriesID int64          `json:"series_id"`
	Kind     string         `json:"kind"`
	Number   sql.NullInt64  `json:"number"`
}

// Fills a date a broadcast schedule left absent, which is a film's normal state.
// The null guard is what makes a real broadcast instant win: without it a tail
// sync, which returns no aired nodes, would replace one every pass.
func (q *Queries) SetWantedItemAirsAtIfNull(ctx context.Context, arg SetWantedItemAirsAtIfNullParams) error {
	_, err := q.db.ExecContext(ctx, setWantedItemAirsAtIfNull,
		arg.AirsAt,
		arg.SeriesID,
		arg.Kind,
		arg.Number,
	)
	return err
}

const setWantedItemHeld = `-- name: SetWantedItemHeld :exec
UPDATE wanted_items SET in_library = ?, held_release_title = ? WHERE id = ?
`

type SetWantedItemHeldParams struct {
	InLibrary        int64  `json:"in_library"`
	HeldReleaseTitle string `json:"held_release_title"`
	ID               int64  `json:"id"`
}

// The one write point for held identity: what the library holds, and which
// release put it there, so an upgrade has something to score against.
func (q *Queries) SetWantedItemHeld(ctx context.Context, arg SetWantedItemHeldParams) error {
	_, err := q.db.ExecContext(ctx, setWantedItemHeld, arg.InLibrary, arg.HeldReleaseTitle, arg.ID)
	return err
}

const setWantedItemInLibrary = `-- name: SetWantedItemInLibrary :exec
UPDATE wanted_items SET in_library = ? WHERE id = ?
`

type SetWantedItemInLibraryParams struct {
	InLibrary int64 `json:"in_library"`
	ID        int64 `json:"id"`
}

func (q *Queries) SetWantedItemInLibrary(ctx context.Context, arg SetWantedItemInLibraryParams) error {
	_, err := q.db.ExecContext(ctx, setWantedItemInLibrary, arg.InLibrary, arg.ID)
	return err
}

const setWantedItemsMonitored = `-- name: SetWantedItemsMonitored :execrows
UPDATE wanted_items SET monitored = ? WHERE id IN (/*SLICE:ids*/?)
`

type SetWantedItemsMonitoredParams struct {
	Monitored int64   `json:"monitored"`
	Ids       []int64 `json:"ids"`
}

// The bulk state-setter behind both monitoring UIs. Unknown ids are simply not
// matched, which is what lets a concurrent series delete cost only those ids.
func (q *Queries) SetWantedItemsMonitored(ctx context.Context, arg SetWantedItemsMonitoredParams) (int64, error) {
	query := setWantedItemsMonitored
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Monitored)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertWantedItem = `-- name: UpsertWantedItem :execrows
INSERT INTO wanted_items (series_id, kind, number, title, in_library, monitored)
VALUES (?, ?, ?, ?, 0, ?)
ON CONFLICT (series_id, kind, number) DO NOTHING
`

type UpsertWantedItemParams struct {
	SeriesID  int64          `json:"series_id"`
	Kind      string         `json:"kind"`
	Number    sql.NullInt64  `json:"number"`
	Title     sql.NullString `json:"title"`
	Monitored int64          `json:"monitored"`
}

// DO NOTHING keeps refresh from ever clobbering an existing item's in_library,
// title or monitored; the row count tells the caller whether the series grew.
func (q *Queries) UpsertWantedItem(ctx context.Context, arg UpsertWantedItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertWantedItem,
		arg.SeriesID,
		arg.Kind,
		arg.Number,
		arg.Title,
		arg.Monitored,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertWantedItemAiring = `-- name: UpsertWantedItemAiring :exec
INSERT INTO wanted_items (series_id, kind, number, airs_at, monitored)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (series_id, kind, number) DO UPDATE SET airs_at = excluded.airs_at
`

type UpsertWantedItemAiringParams struct {
	SeriesID  int64          `json:"series_id"`
	Kind      string         `json:"kind"`
	Number    sql.NullInt64  `json:"number"`
	AirsAt    sql.NullString `json:"airs_at"`
	Monitored int64          `json:"monitored"`
}

// Creating the item matters for a null-count long-runner: the schedule is the
// only source that knows its episodes exist. Only airs_at moves on conflict, so
// a stored monitored flag survives every resync.
func (q *Queries) UpsertWantedItemAiring(ctx context.Context, arg UpsertWantedItemAiringParams) error {
	_, err := q.db.ExecContext(ctx, upsertWantedItemAiring,
		arg.SeriesID,
		arg.Kind,
		arg.Number,
		arg.AirsAt,
		arg.Monitored,
	)
	return err
}
