// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wanted_queue.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const countSeriesByIDs = `-- name: CountSeriesByIDs :one
SELECT COUNT(*) FROM series WHERE id IN (/*SLICE:ids*/?)
`

// How many of these ids are real series, so a bulk action can reject an unknown
// one in a single round trip rather than a lookup per id.
func (q *Queries) CountSeriesByIDs(ctx context.Context, ids []int64) (int64, error) {
	query := countSeriesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listActiveBlocklistCounts = `-- name: ListActiveBlocklistCounts :many
SELECT series_id, COUNT(*) AS entries
FROM release_blocklist
WHERE series_id IN (/*SLICE:series_ids*/?)
  AND (blocked_until IS NULL OR blocked_until > ?)
GROUP BY series_id
`

type ListActiveBlocklistCountsParams struct {
	SeriesIds    []int64        `json:"series_ids"`
	BlockedUntil sql.NullString `json:"blocked_until"`
}

type ListActiveBlocklistCountsRow struct {
	SeriesID int64 `json:"series_id"`
	Entries  int64 `json:"entries"`
}

// How many releases each series is currently refusing, for the reason column.
// Per series rather than per item because that is the blocklist's own scope.
// Scoped to the page's series, like the item fetches beside it: the whole table
// was aggregated to read out at most one page's worth. A NULL blocked_until is
// permanent.
func (q *Queries) ListActiveBlocklistCounts(ctx context.Context, arg ListActiveBlocklistCountsParams) ([]ListActiveBlocklistCountsRow, error) {
	query := listActiveBlocklistCounts
	var queryParams []interface{}
	if len(arg.SeriesIds) > 0 {
		for _, v := range arg.SeriesIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:series_ids*/?", strings.Repeat(",?", len(arg.SeriesIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:series_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.BlockedUntil)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveBlocklistCountsRow{}
	for rows.Next() {
		var i ListActiveBlocklistCountsRow
		if err := rows.Scan(&i.SeriesID, &i.Entries); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCutoffItemsBySeries = `-- name: ListCutoffItemsBySeries :many
SELECT w.id, w.series_id, w.kind, w.number, w.title, w.in_library, w.airs_at, w.held_release_title, w.monitored,
       g.status        AS grab_status,
       g.release_title AS grab_release_title,
       g.last_error    AS grab_last_error
FROM wanted_items w
JOIN grabs g ON g.wanted_item_id = w.id
WHERE w.series_id IN (/*SLICE:series_ids*/?)
  AND w.in_library = 1
  AND (? = 1 OR w.monitored = 1)
  AND w.held_release_title != ''
  AND g.status IN ('imported', 'failed', 'grabbed')
ORDER BY w.series_id, w.number
`

type ListCutoffItemsBySeriesParams struct {
	SeriesIds []int64     `json:"series_ids"`
	Column2   interface{} `json:"column_2"`
}

type ListCutoffItemsBySeriesRow struct {
	ID               int64          `json:"id"`
	SeriesID         int64          `json:"series_id"`
	Kind             string         `json:"kind"`
	Number           sql.NullInt64  `json:"number"`
	Title            sql.NullString `json:"title"`
	InLibrary        int64          `json:"in_library"`
	AirsAt           sql.NullString `json:"airs_at"`
	HeldReleaseTitle string         `json:"held_release_title"`
	Monitored        int64          `json:"monitored"`
	GrabStatus       string         `json:"grab_status"`
	GrabReleaseTitle string         `json:"grab_release_title"`
	GrabLastError    sql.NullString `json:"grab_last_error"`
}

// Every rateable held item behind one page of candidate groups; scoring and the
// cutoff test happen in Go under the one profile snapshot per series. The grab
// join is inner and its status set matches the series page's, so a group's
// items are exactly what made its series a candidate.
func (q *Queries) ListCutoffItemsBySeries(ctx context.Context, arg ListCutoffItemsBySeriesParams) ([]ListCutoffItemsBySeriesRow, error) {
	query := listCutoffItemsBySeries
	var queryParams []interface{}
	if len(arg.SeriesIds) > 0 {
		for _, v := range arg.SeriesIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:series_ids*/?", strings.Repeat(",?", len(arg.SeriesIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:series_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Column2)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCutoffItemsBySeriesRow{}
	for rows.Next() {
		var i ListCutoffItemsBySeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Kind,
			&i.Number,
			&i.Title,
			&i.InLibrary,
			&i.AirsAt,
			&i.HeldReleaseTitle,
			&i.Monitored,
			&i.GrabStatus,
			&i.GrabReleaseTitle,
			&i.GrabLastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCutoffSeriesPage = `-- name: ListCutoffSeriesPage :many
SELECT s.id, s.title, s.monitored,
       qp.id           AS profile_id,
       qp.name         AS profile_name,
       qp.cutoff_score AS profile_cutoff_score
FROM series s
JOIN quality_profiles qp ON qp.id = s.quality_profile_id
WHERE qp.upgrades_enabled = 1
  AND (? = 1 OR s.monitored = 1)
  AND EXISTS (
      SELECT 1
      FROM wanted_items w
      JOIN grabs g ON g.wanted_item_id = w.id
      WHERE w.series_id = s.id
        AND w.in_library = 1
        AND (? = 1 OR w.monitored = 1)
        AND w.held_release_title != ''
        AND g.status IN ('imported', 'failed', 'grabbed')
  )
  AND (s.title > ? OR (s.title = ? AND s.id > ?))
ORDER BY s.title, s.id
LIMIT ?
`

type ListCutoffSeriesPageParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Title   string      `json:"title"`
	Title_2 string      `json:"title_2"`
	ID      int64       `json:"id"`
	Limit   int64       `json:"limit"`
}

type ListCutoffSeriesPageRow struct {
	ID                 int64  `json:"id"`
	Title              string `json:"title"`
	Monitored          int64  `json:"monitored"`
	ProfileID          int64  `json:"profile_id"`
	ProfileName        string `json:"profile_name"`
	ProfileCutoffScore int64  `json:"profile_cutoff_score"`
}

// Candidate groups for Cutoff Unmet: series on an upgrading profile holding
// anything the upgrade pool could act on. The status set is the sweep's pool
// (imported, failed -- see loadSweepItems) plus grabbed, which is an upgrade
// already in flight and worth showing as such. import_deferred is deliberately
// out: that item's fix is the Activity queue's, and a grab from here would
// overwrite the deferred row and orphan its payload. Whether a held release
// actually scores below the cutoff needs the parser and is settled in Go, so a
// series here may contribute no group and the caller scans on. Ordered by title
// -- this listing is an inventory, not a queue, so alphabetical reads best --
// with the id tie-break ascending and a zero cursor as the natural top.
func (q *Queries) ListCutoffSeriesPage(ctx context.Context, arg ListCutoffSeriesPageParams) ([]ListCutoffSeriesPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listCutoffSeriesPage,
		arg.Column1,
		arg.Column2,
		arg.Title,
		arg.Title_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCutoffSeriesPageRow{}
	for rows.Next() {
		var i ListCutoffSeriesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Monitored,
			&i.ProfileID,
			&i.ProfileName,
			&i.ProfileCutoffScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissingItemsBySeries = `-- name: ListMissingItemsBySeries :many
SELECT w.id, w.series_id, w.kind, w.number, w.title, w.in_library, w.airs_at, w.held_release_title, w.monitored,
       g.status        AS grab_status,
       g.release_title AS grab_release_title,
       g.last_error    AS grab_last_error,
       g.created_at    AS grab_created_at,
       p.outcome       AS pass_outcome,
       p.source        AS pass_source,
       p.release_title AS pass_release_title,
       p.detail        AS pass_detail,
       p.held_until    AS pass_held_until,
       p.recorded_at   AS pass_recorded_at
FROM wanted_items w
LEFT JOIN grabs g ON g.wanted_item_id = w.id
LEFT JOIN pass_outcomes p ON p.wanted_item_id = w.id
WHERE w.series_id IN (/*SLICE:series_ids*/?)
  AND w.in_library = 0
  AND (g.wanted_item_id IS NULL OR g.status = 'failed')
  AND (? = 1 OR w.monitored = 1)
  AND (? = 1 OR w.kind = 'movie' OR w.airs_at IS NULL OR w.airs_at <= ?)
ORDER BY w.series_id, w.number
`

type ListMissingItemsBySeriesParams struct {
	SeriesIds []int64        `json:"series_ids"`
	Column2   interface{}    `json:"column_2"`
	Column3   interface{}    `json:"column_3"`
	AirsAt    sql.NullString `json:"airs_at"`
}

type ListMissingItemsBySeriesRow struct {
	ID               int64          `json:"id"`
	SeriesID         int64          `json:"series_id"`
	Kind             string         `json:"kind"`
	Number           sql.NullInt64  `json:"number"`
	Title            sql.NullString `json:"title"`
	InLibrary        int64          `json:"in_library"`
	AirsAt           sql.NullString `json:"airs_at"`
	HeldReleaseTitle string         `json:"held_release_title"`
	Monitored        int64          `json:"monitored"`
	GrabStatus       sql.NullString `json:"grab_status"`
	GrabReleaseTitle sql.NullString `json:"grab_release_title"`
	GrabLastError    sql.NullString `json:"grab_last_error"`
	GrabCreatedAt    sql.NullString `json:"grab_created_at"`
	PassOutcome      sql.NullString `json:"pass_outcome"`
	PassSource       sql.NullString `json:"pass_source"`
	PassReleaseTitle sql.NullString `json:"pass_release_title"`
	PassDetail       sql.NullString `json:"pass_detail"`
	PassHeldUntil    sql.NullString `json:"pass_held_until"`
	PassRecordedAt   sql.NullString `json:"pass_recorded_at"`
}

// The items behind one page of groups. Same predicates as the series page, so a
// group and its items are computed from one reading of the world; the series
// half of the monitoring filter is the series page's business, since every id
// here came from it. Number ascends within a series deliberately: a back catalogue
// drains forwards, and episodes enumerate forwards however their dates fall.
// Both joins are 1:1, so neither multiplies rows. The grab's created_at rides
// along because the reason column ranks a stored pass outcome against it: an
// answer older than the grab is one the grab has already superseded.
func (q *Queries) ListMissingItemsBySeries(ctx context.Context, arg ListMissingItemsBySeriesParams) ([]ListMissingItemsBySeriesRow, error) {
	query := listMissingItemsBySeries
	var queryParams []interface{}
	if len(arg.SeriesIds) > 0 {
		for _, v := range arg.SeriesIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:series_ids*/?", strings.Repeat(",?", len(arg.SeriesIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:series_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Column2)
	queryParams = append(queryParams, arg.Column3)
	queryParams = append(queryParams, arg.AirsAt)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMissingItemsBySeriesRow{}
	for rows.Next() {
		var i ListMissingItemsBySeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Kind,
			&i.Number,
			&i.Title,
			&i.InLibrary,
			&i.AirsAt,
			&i.HeldReleaseTitle,
			&i.Monitored,
			&i.GrabStatus,
			&i.GrabReleaseTitle,
			&i.GrabLastError,
			&i.GrabCreatedAt,
			&i.PassOutcome,
			&i.PassSource,
			&i.PassReleaseTitle,
			&i.PassDetail,
			&i.PassHeldUntil,
			&i.PassRecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissingSeriesPage = `-- name: ListMissingSeriesPage :many

SELECT s.id, s.title, s.monitored, s.last_searched_at, s.next_search_at,
       MAX(COALESCE(w.airs_at, '')) AS latest_missing_air,
       COUNT(*)                     AS missing
FROM wanted_items w
JOIN series s ON s.id = w.series_id
LEFT JOIN grabs g ON g.wanted_item_id = w.id
WHERE w.in_library = 0
  AND (g.wanted_item_id IS NULL OR g.status = 'failed')
  AND (? = 1 OR (s.monitored = 1 AND w.monitored = 1))
  AND (? = 1 OR w.kind = 'movie' OR w.airs_at IS NULL OR w.airs_at <= ?)
GROUP BY s.id
HAVING MAX(COALESCE(w.airs_at, '')) < ? OR (MAX(COALESCE(w.airs_at, '')) = ? AND s.id > ?)
ORDER BY MAX(COALESCE(w.airs_at, '')) DESC, s.id
LIMIT ?
`

type ListMissingSeriesPageParams struct {
	Column1  interface{}    `json:"column_1"`
	Column2  interface{}    `json:"column_2"`
	AirsAt   sql.NullString `json:"airs_at"`
	AirsAt_2 sql.NullString `json:"airs_at_2"`
	AirsAt_3 sql.NullString `json:"airs_at_3"`
	ID       int64          `json:"id"`
	Limit    int64          `json:"limit"`
}

type ListMissingSeriesPageRow struct {
	ID               int64          `json:"id"`
	Title            string         `json:"title"`
	Monitored        int64          `json:"monitored"`
	LastSearchedAt   sql.NullString `json:"last_searched_at"`
	NextSearchAt     sql.NullString `json:"next_search_at"`
	LatestMissingAir interface{}    `json:"latest_missing_air"`
	Missing          int64          `json:"missing"`
}

// The cross-series wanted queue (issue #150): Missing and Cutoff Unmet, both
// keyset-paginated. A missing set is unbounded -- a fresh library add can put
// hundreds of items in it at once -- so neither list may load whole.
// NOTE: keep comments in this file ASCII-only. sqlc's sqlite codegen miscounts
// byte vs. rune offsets and silently truncates the emitted SQL on a multi-byte
// character. See CLAUDE.md.
// The Missing tab's pagination unit is the series, so a group can never split
// across a page boundary. The wanted half is the sweep's predicate character
// for character (the EXISTS body of ListSeriesDueWantedSearch), which is what
// keeps this page honest about what automation will go after; an in-flight
// grab is absent by construction, being Activity's to show. Monitoring and the
// unaired cut are display filters, not exclusions: a row has to stay visible
// after the click that hid it, or there is no way back. The unaired cut skips a
// movie because its date means something else: an episode's air date is when it
// becomes acquirable, so withholding it until then is complete information,
// while a film's is the theatrical premiere -- only the earliest it could be,
// months ahead of anything grabbable. Hiding it would drop the whole title from
// this page, where hiding one episode still leaves its series listed. Groups are ordered
// newest missing broadcast first, all-undated series last: COALESCE sorts a
// null air date below every timestamp, and lexicographic compare on the one
// stored layout is chronological. The keyset lives in HAVING because it binds
// on the aggregate; a first page passes a sentinel above every stored value so
// one query serves every page. The count is the whole group even when the
// handler caps the items it returns for one.
func (q *Queries) ListMissingSeriesPage(ctx context.Context, arg ListMissingSeriesPageParams) ([]ListMissingSeriesPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listMissingSeriesPage,
		arg.Column1,
		arg.Column2,
		arg.AirsAt,
		arg.AirsAt_2,
		arg.AirsAt_3,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMissingSeriesPageRow{}
	for rows.Next() {
		var i ListMissingSeriesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Monitored,
			&i.LastSearchedAt,
			&i.NextSearchAt,
			&i.LatestMissingAir,
			&i.Missing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
