#!/usr/bin/env bash
#
# Generate THIRD-PARTY-NOTICES.md — the third-party attribution file required
# by the licenses of our dependencies (MIT/BSD/ISC/Apache-2.0/MPL-2.0/OFL-1.1
# all require the copyright + license text to travel with redistributed copies,
# and the binary embeds them all).
#
# Two sources, matching what actually ships:
#   - Go:       the modules *linked into the built binary* (`go version -m`),
#               not the full module graph — goose pulls DB drivers we never
#               link, and those must not be attributed. Copies LICENSE, COPYING
#               and (per Apache-2.0 §4(d)) any NOTICE file each module carries.
#   - Frontend: production deps only (`license-checker-rseidelsohn --production`);
#               devDependencies (vite, oxlint, tsc, lightningcss, …) are build
#               tools that never reach web/dist, so they are not attributed.
#
# Run via `make notices`. Do not hand-edit the output.
set -euo pipefail

# Deterministic sort order across platforms (macOS dev vs Linux CI) — the CI
# freshness check diffs regenerated output against the committed file.
export LC_ALL=C

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/THIRD-PARTY-NOTICES.md"
TMP_BIN="$(mktemp -t transpondarrd-notices.XXXXXX)"
trap 'rm -f "$TMP_BIN"' EXIT

echo "==> building a throwaway binary to read its linked module set"
# CGO-free, matching the release build. web/dist already holds a committed
# .gitkeep so the embed resolves even without a fresh frontend build.
CGO_ENABLED=0 go build -o "$TMP_BIN" "$ROOT/cmd/transpondarrd"

echo "==> collecting Go module notices"
# Header
{
  cat <<'HEADER'
# Third-Party Notices

Transpondarr is distributed under the [Apache License 2.0](LICENSE) as a single
binary that statically links the Go modules below and embeds the compiled
frontend assets. This file reproduces the copyright and license notices those
dependencies require us to carry.

**Generated by `make notices` — do not edit by hand.** Regenerate after changing
dependencies. Only components that actually ship are listed: Go modules linked
into the binary (not the full module graph) and frontend production
dependencies (not build-time devDependencies).

## Go modules (statically linked into the binary)

HEADER
} > "$OUT"

# `go version -m` prints tab-indented `dep <module> <version> <hash>` lines, and
# `=> <module> <version>` for any replace directive (none today, but handled).
go version -m "$TMP_BIN" \
  | awk '$1=="dep" || $1=="=>" {print $2"@"$3}' \
  | sort -u \
  | while IFS= read -r modver; do
      [ -z "$modver" ] && continue
      # Ask the toolchain for the module's on-disk cache dir — avoids fragile
      # hand-rolled path case-encoding (Foo -> !foo).
      dir="$(go mod download -json "$modver" 2>/dev/null \
             | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{process.stdout.write(JSON.parse(s).Dir||"")}catch(e){}})')"
      if [ -z "$dir" ] || [ ! -d "$dir" ]; then
        echo "  WARN: no cache dir for $modver — skipped" >&2
        continue
      fi
      printf '### %s\n\n' "$modver" >> "$OUT"
      found=""
      while IFS= read -r f; do
        found=1
        printf '```\n' >> "$OUT"
        # Strip CRLF — some upstream license files use it, and the CI freshness
        # check diffs raw bytes on Linux where git applies no normalization.
        sed 's/\r$//' "$f" >> "$OUT"
        printf '\n```\n\n' >> "$OUT"
      done < <(find "$dir" -maxdepth 1 -type f \
                 \( -iname 'LICENSE*' -o -iname 'COPYING*' -o -iname 'NOTICE*' \) \
                 | sort)
      if [ -z "$found" ]; then
        echo "  WARN: no license file found for $modver" >&2
        printf '_No license file bundled in the module. See %s_\n\n' \
          "https://pkg.go.dev/${modver%@*}?tab=licenses" >> "$OUT"
      fi
    done

echo "==> collecting frontend (production) notices"
{
  printf '## Frontend production dependencies (embedded in web/dist)\n\n'
} >> "$OUT"

( cd "$ROOT/frontend"
  npx --yes license-checker-rseidelsohn@5.0.1 --production --json 2>/dev/null
) | node -e '
  let s="";
  process.stdin.on("data",d=>s+=d).on("end",()=>{
    const fs=require("fs");
    const j=JSON.parse(s);
    const out=[];
    for (const key of Object.keys(j).sort()) {
      const v=j[key];
      out.push(`### ${key} — ${v.licenses||"UNKNOWN"}`);
      out.push("");
      if (v.repository) { out.push(v.repository); out.push(""); }
      let text="";
      if (v.licenseFile) { try { text=fs.readFileSync(v.licenseFile,"utf8").trim().replace(/\r\n?/g,"\n"); } catch(e){} }
      if (text) { out.push("```"); out.push(text); out.push("```"); }
      else { out.push(`_License: ${v.licenses||"UNKNOWN"} (no license file bundled)._`); }
      out.push("");
    }
    process.stdout.write(out.join("\n"));
  });
' >> "$OUT"

echo "==> wrote $OUT"
