/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/activity/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent grab and import events across the library, newest first */
        get: operations["list-activity-history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every in-flight grab across the library, with live client state */
        get: operations["get-activity-queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blocklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How much of the library is being skipped, and whether memory is suppressed */
        get: operations["get-blocklist-summary"];
        put?: never;
        post?: never;
        /** Forget every remembered release across the library */
        delete: operations["clear-blocklist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/browse/season": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chart a broadcast season, served from the per-season cache */
        get: operations["browse-season"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wanted items airing in a range, with derived acquisition state */
        get: operations["get-calendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/download/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test connectivity to the configured download client */
        post: operations["test-download-client"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check (public, no API key required) */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexer/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the configured indexer for releases */
        get: operations["search-indexer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search AniList for titles to add */
        get: operations["search-metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List quality profiles with their ranked groups and usage counts */
        get: operations["list-quality-profiles"];
        put?: never;
        /** Create a quality profile */
        post: operations["create-quality-profile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a quality profile, replacing its ranked groups */
        put: operations["update-quality-profile"];
        post?: never;
        /** Delete a quality profile, migrating its series to reassign_to first */
        delete: operations["delete-quality-profile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List monitored series */
        get: operations["list-series"];
        put?: never;
        /** Add a series by AniList id (expands its wanted items) */
        post: operations["add-series"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a series with its wanted items and their acquisition state */
        get: operations["get-series"];
        put?: never;
        post?: never;
        /** Delete a series and everything tracked for it; library files are never touched */
        delete: operations["delete-series"];
        options?: never;
        head?: never;
        /** Update whether a series is monitored */
        patch: operations["set-series-monitored"];
        trace?: never;
    };
    "/api/v1/series/{id}/blocklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List releases remembered as failed for a series */
        get: operations["list-series-blocklist"];
        put?: never;
        post?: never;
        /** Unblock every remembered release for a series */
        delete: operations["clear-series-blocklist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{id}/blocklist/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unblock a release, making it eligible again */
        delete: operations["clear-series-blocklist-entry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{id}/grab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grab a chosen release: add it to the download client and record it against the wanted items it covers */
        post: operations["grab-series-release"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{id}/grabs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List grab/import history for a series */
        get: operations["list-series-grabs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{id}/pinned-group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Pin a release group for a series (an absolute tier above profile scoring) */
        put: operations["set-series-pinned-group"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign a quality profile to a series */
        put: operations["assign-series-profile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find and match indexer releases against a series' wanted items (read-only; does not grab) */
        get: operations["search-series-releases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the effective runtime configuration (secrets masked) */
        get: operations["get-settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/apikey/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a new API key (invalidates the old one) */
        post: operations["regenerate-api-key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/automation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update the global automation policy (applies on the next job tick) */
        put: operations["update-automation-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update the qBittorrent download client (rebuilds it live) */
        put: operations["update-download-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/download/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test qBittorrent connectivity for the given (unsaved) values */
        post: operations["test-download-settings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/indexer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update the Torznab indexer (rebuilds it live) */
        put: operations["update-indexer-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/indexer/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Torznab connectivity for the given (unsaved) values */
        post: operations["test-indexer-settings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update the library import target (rebuilds it live) */
        put: operations["update-library-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/library/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test that the given library directory exists and is writable */
        post: operations["test-library-settings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update the notification adapters (rebuilds the dispatcher live) */
        put: operations["update-notifications-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/notifications/discord/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test notification to the given (unsaved) Discord webhook */
        post: operations["test-notify-discord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/notifications/ntfy/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test notification to the given (unsaved) ntfy topic */
        post: operations["test-notify-ntfy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/notifications/webhook/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test notification to the given (unsaved) webhook URL */
        post: operations["test-notify-webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status of the runner-managed background jobs */
        get: operations["list-jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/jobs/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a background job now
         * @description Queues the job on its own goroutine and returns immediately. A trigger during a run queues one follow-up run; further triggers coalesce into that pending one.
         */
        post: operations["run-job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityEventDTO: {
            created_at: string;
            /** @description Why a failed event failed */
            detail?: string;
            /** Format: int64 */
            id: number;
            infohash: string;
            /** Format: int64 */
            item_number: number;
            release_title: string;
            /** Format: int64 */
            series_id: number;
            series_title: string;
            /** @enum {string} */
            status: "grabbed" | "imported" | "import_deferred" | "failed";
        };
        ActivityHistoryOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ActivityHistoryOutputBody.json
             */
            readonly $schema?: string;
            events: components["schemas"]["ActivityEventDTO"][];
            /** @description Absent on the last page */
            next_cursor?: string;
        };
        ActivityQueueOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ActivityQueueOutputBody.json
             */
            readonly $schema?: string;
            /** @description False when the download client is missing or did not answer; rows then carry grab state only */
            client_ok: boolean;
            items: components["schemas"]["QueueItemDTO"][];
        };
        AddSeriesInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AddSeriesInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description AniList media id to add
             */
            anilist_id: number;
            /** @description Whether to monitor for downloads (default true) */
            monitored?: boolean;
        };
        ApiKeyOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ApiKeyOutputBody.json
             */
            readonly $schema?: string;
            api_key: string;
        };
        AssignSeriesProfileInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AssignSeriesProfileInputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            profile_id: number;
        };
        AssignSeriesProfileOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AssignSeriesProfileOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            profile_id: number;
            /** Format: int64 */
            series_id: number;
        };
        AuthSettingsDTO: {
            configured: boolean;
            /** @description enabled or local */
            required: string;
            username: string;
        };
        AutomationInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AutomationInputBody.json
             */
            readonly $schema?: string;
            enabled: boolean;
            /**
             * Format: int64
             * @description Global pinned-group wait; 0 disables waiting
             */
            pin_delay_hours: number;
        };
        AutomationSettingsDTO: {
            enabled: boolean;
            /** Format: int64 */
            pin_delay_hours: number;
        };
        BlocklistEntryDTO: {
            /** @description Whether the block applies right now */
            active: boolean;
            /**
             * Format: date-time
             * @description When the block lapses; absent means permanent
             */
            blocked_until?: string;
            created_at: string;
            /**
             * Format: int64
             * @description How many times this release has failed; the third failure blocks it permanently
             */
            failures: number;
            /** Format: int64 */
            id: number;
            infohash?: string;
            reason: string;
            release_title: string;
        };
        BlocklistSummaryOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BlocklistSummaryOutputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Releases being skipped right now
             */
            blocked: number;
            breaker: components["schemas"]["BreakerDTO"];
            /**
             * Format: int64
             * @description How many series they span
             */
            series: number;
        };
        BreakerDTO: {
            /**
             * Format: int64
             * @description Distinct wanted items that failed inside the window, counting one item per release so a batch cannot inflate it
             */
            items: number;
            open: boolean;
            /**
             * Format: date-time
             * @description When the breaker opened; absent while closed
             */
            since?: string;
            /**
             * Format: int64
             * @description How many distinct items opens the breaker
             */
            threshold: number;
            /** Format: int64 */
            window_minutes: number;
        };
        BrowseSeasonOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BrowseSeasonOutputBody.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["SeasonEntryDTO"][];
            /** @enum {string} */
            season: "winter" | "spring" | "summer" | "fall";
            /** Format: int64 */
            year: number;
        };
        CalendarItemDTO: {
            /**
             * Format: date-time
             * @description Broadcast time (RFC 3339 UTC)
             */
            airs_at: string;
            /** Format: int64 */
            id: number;
            /** @description Why the last import attempt failed (status stuck) */
            import_error?: string;
            monitored: boolean;
            name?: string;
            /** Format: int64 */
            number: number;
            /** Format: int64 */
            series_id: number;
            series_title: string;
            /**
             * @description Derived acquisition state
             * @enum {string}
             */
            status: "have" | "downloading" | "stuck" | "deferred" | "wanted";
        };
        CalendarOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CalendarOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["CalendarItemDTO"][];
            /** @description Monitored series missing episodes with no schedule data */
            unscheduled: components["schemas"]["UnscheduledSeriesDTO"][];
        };
        CandidateDTO: {
            /** Format: int64 */
            anilist_id: number;
            cover_url?: string;
            english?: string;
            /** Format: int64 */
            episodes: number;
            format?: string;
            native?: string;
            romaji?: string;
            status?: string;
            /** Format: int64 */
            year?: number;
        };
        CandidateReleaseDTO: {
            download_url: string;
            dual_audio: boolean;
            eligible: boolean;
            /** @description Why the profile refuses this release; empty when eligible */
            ineligible_reason?: string;
            infohash?: string;
            items?: number[];
            matched: boolean;
            /** @description Release group is the series' pinned group; ranks above profile score when eligible */
            pinned: boolean;
            reason: string;
            release_group?: string;
            resolution?: string;
            /**
             * Format: int64
             * @description Profile score; ranking is by this, seeders only break ties
             */
            score: number;
            /** @description Per-axis contributions summing to score */
            score_parts?: components["schemas"]["ScorePartDTO"][];
            /** Format: int64 */
            seeders: number;
            /** Format: int64 */
            size: number;
            title: string;
        };
        ClearedOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ClearedOutputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description How many entries were forgotten
             */
            cleared: number;
        };
        DetailItemDTO: {
            /**
             * Format: date-time
             * @description Broadcast time (RFC 3339, Japanese broadcast clock); absent when the provider publishes none
             */
            airs_at?: string;
            have: boolean;
            /** Format: int64 */
            id: number;
            /** @description Why the last import attempt failed (status stuck) */
            import_error?: string;
            name?: string;
            /** Format: int64 */
            number: number;
            release_title?: string;
            /**
             * @description Derived acquisition state
             * @enum {string}
             */
            status: "have" | "downloading" | "stuck" | "deferred" | "wanted";
        };
        DownloadInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DownloadInputBody.json
             */
            readonly $schema?: string;
            category?: string;
            /** @description Leave empty to keep the stored password */
            password?: string;
            url?: string;
            user?: string;
        };
        DownloadSettingsDTO: {
            category: string;
            configured: boolean;
            password_set: boolean;
            url: string;
            user: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][];
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        GeneralSettingsDTO: {
            addr: string;
            /** @description Current API key (visible to authenticated callers) */
            api_key: string;
            data_dir: string;
            db_path: string;
            version: string;
        };
        GrabEventDTO: {
            created_at: string;
            /** @description Why a failed event failed */
            detail?: string;
            /** Format: int64 */
            id: number;
            infohash: string;
            /** Format: int64 */
            item_number: number;
            release_title: string;
            /** @enum {string} */
            status: "grabbed" | "imported" | "import_deferred" | "failed";
        };
        GrabSeriesInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GrabSeriesInputBody.json
             */
            readonly $schema?: string;
            /** @description download_url of a matched release from the series search */
            download_url: string;
            /** @description Add the torrent stopped (no data transfer) — useful for testing the grab flow */
            paused?: boolean;
        };
        GrabSeriesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GrabSeriesOutputBody.json
             */
            readonly $schema?: string;
            /** @description Set when the grabbed release falls outside the series' quality profile — informational, the grab still succeeds */
            ineligible_reason?: string;
            infohash: string;
            items: number[];
            /** @example success */
            outcome: string;
            release: string;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /** @example ok */
            status: string;
            version: string;
        };
        IndexerInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/IndexerInputBody.json
             */
            readonly $schema?: string;
            /** @description Leave empty to keep the stored API key */
            apikey?: string;
            name?: string;
            url?: string;
        };
        IndexerSettingsDTO: {
            apikey_set: boolean;
            configured: boolean;
            name: string;
            url: string;
        };
        JobStatusDTO: {
            /** Format: int64 */
            interval_ms: number;
            /**
             * Format: double
             * @description Fractional: a sub-millisecond sweep would otherwise always report 0
             */
            last_duration_ms: number;
            last_error?: string;
            /** @description RFC3339 UTC; absent until the job has run */
            last_run?: string;
            name: string;
            /** @description RFC3339 UTC; absent while the runner is not running */
            next_run?: string;
            running: boolean;
        };
        LibraryInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LibraryInputBody.json
             */
            readonly $schema?: string;
            dir?: string;
            /** @enum {string} */
            mode?: "auto" | "hardlink" | "copy";
        };
        LibrarySettingsDTO: {
            configured: boolean;
            dir: string;
            mode: string;
        };
        ListJobsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListJobsOutputBody.json
             */
            readonly $schema?: string;
            jobs: components["schemas"]["JobStatusDTO"][];
        };
        ListProfilesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListProfilesOutputBody.json
             */
            readonly $schema?: string;
            profiles: components["schemas"]["QualityProfileDTO"][];
        };
        ListSeriesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListSeriesOutputBody.json
             */
            readonly $schema?: string;
            series: components["schemas"]["SeriesDTO"][];
        };
        NotificationsInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/NotificationsInputBody.json
             */
            readonly $schema?: string;
            discord: components["schemas"]["NotifyAdapterInput"];
            ntfy: components["schemas"]["NtfyInput"];
            webhook: components["schemas"]["NotifyAdapterInput"];
        };
        NotificationsSettingsDTO: {
            discord: components["schemas"]["NotifyAdapterDTO"];
            ntfy: components["schemas"]["NtfySettingsDTO"];
            webhook: components["schemas"]["NotifyAdapterDTO"];
        };
        NotifyAdapterDTO: {
            configured: boolean;
            on_grab_failed: boolean;
            on_grabbed: boolean;
            on_imported: boolean;
            on_series_added: boolean;
            on_stuck: boolean;
            url: string;
        };
        NotifyAdapterInput: {
            on_grab_failed: boolean;
            on_grabbed: boolean;
            on_imported: boolean;
            on_series_added: boolean;
            on_stuck: boolean;
            url?: string;
        };
        NtfyInput: {
            on_grab_failed: boolean;
            on_grabbed: boolean;
            on_imported: boolean;
            on_series_added: boolean;
            on_stuck: boolean;
            server?: string;
            /** @description Leave empty to keep the stored token */
            token?: string;
            topic?: string;
        };
        NtfySettingsDTO: {
            configured: boolean;
            on_grab_failed: boolean;
            on_grabbed: boolean;
            on_imported: boolean;
            on_series_added: boolean;
            on_stuck: boolean;
            server: string;
            token_set: boolean;
            topic: string;
        };
        ProfileBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProfileBody.json
             */
            readonly $schema?: string;
            /** @description h264, h265 or av1; empty for no preference */
            codec_pref?: string;
            /** @description Ranked group preference, most preferred first */
            groups?: components["schemas"]["ProfileGroupDTO"][];
            /** @description Axis values a release must never carry, e.g. hardsub */
            hard_excludes?: string[];
            /**
             * Format: int64
             * @description Floor: candidates scoring below are ineligible
             */
            min_score?: number;
            name: string;
            prefer_dual_audio?: boolean;
            /** @description web, bd, tv or dvd; empty for no preference */
            preferred_source?: string;
            /** @description Best first; an unlisted resolution scores zero */
            resolution_order?: string[];
            /** @description softsub or hardsub; empty for no preference */
            sub_pref?: string;
        };
        ProfileGroupDTO: {
            /** @description Never take this group, at any quality */
            blocked?: boolean;
            /** @description Release group name; array order is the preference rank */
            name: string;
        };
        QualityProfileDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/QualityProfileDTO.json
             */
            readonly $schema?: string;
            codec_pref: string;
            groups: components["schemas"]["ProfileGroupDTO"][];
            hard_excludes: string[];
            /** Format: int64 */
            id: number;
            is_default: boolean;
            /** Format: int64 */
            min_score: number;
            name: string;
            prefer_dual_audio: boolean;
            preferred_source: string;
            resolution_order: string[];
            /**
             * Format: int64
             * @description How many series are assigned this profile
             */
            series_count: number;
            sub_pref: string;
        };
        QueueItemDTO: {
            /**
             * @description Live torrent state; absent when the client is unreachable
             * @enum {string}
             */
            client_state?: "downloading" | "complete" | "stalled" | "checking" | "paused" | "error" | "unknown";
            created_at: string;
            /** Format: int64 */
            id: number;
            /** @description Why the completed download cannot import (stuck rows) */
            import_error?: string;
            infohash: string;
            /** Format: int64 */
            item_number: number;
            /** Format: double */
            progress?: number;
            release_title: string;
            /** Format: int64 */
            series_id: number;
            series_title: string;
            /** @enum {string} */
            status: "downloading" | "stuck" | "deferred";
        };
        ReleaseDTO: {
            download_url: string;
            indexer: string;
            infohash?: string;
            /** Format: int64 */
            seeders: number;
            /** Format: int64 */
            size: number;
            title: string;
        };
        ScorePartDTO: {
            label: string;
            /** Format: int64 */
            points: number;
        };
        SearchIndexerOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SearchIndexerOutputBody.json
             */
            readonly $schema?: string;
            results: components["schemas"]["ReleaseDTO"][];
        };
        SearchMetadataOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SearchMetadataOutputBody.json
             */
            readonly $schema?: string;
            results: components["schemas"]["CandidateDTO"][];
        };
        SearchSeriesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SearchSeriesOutputBody.json
             */
            readonly $schema?: string;
            results: components["schemas"]["CandidateReleaseDTO"][];
            series: string;
            term: string;
        };
        SeasonEntryDTO: {
            /** Format: int64 */
            anilist_id: number;
            /** Format: int64 */
            average_score: number;
            cover_url?: string;
            /** @description Provider-formatted HTML synopsis */
            description?: string;
            english?: string;
            /** Format: int64 */
            episodes: number;
            format?: string;
            genres: string[];
            native?: string;
            /** Format: date-time */
            next_airs_at?: string;
            /** Format: int64 */
            next_episode?: number;
            romaji?: string;
            /**
             * Format: int64
             * @description Local series id when tracked
             */
            series_id?: number;
            status?: string;
            studio?: string;
            tracked: boolean;
        };
        SeriesBlocklistOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SeriesBlocklistOutputBody.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["BlocklistEntryDTO"][];
            series: string;
        };
        SeriesDTO: {
            format: string;
            /** Format: int64 */
            have: number;
            /** Format: int64 */
            id: number;
            monitored: boolean;
            title: string;
            /** Format: int64 */
            total: number;
        };
        SeriesDetailDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SeriesDetailDTO.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            anilist_id: number;
            format: string;
            /** Format: int64 */
            id: number;
            items: components["schemas"]["WantedItemDTO"][];
            monitored: boolean;
            title: string;
        };
        SeriesDetailReadDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SeriesDetailReadDTO.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            anilist_id?: number;
            cover_url?: string;
            english?: string;
            format: string;
            /** Format: int64 */
            id: number;
            items: components["schemas"]["DetailItemDTO"][];
            monitored: boolean;
            native?: string;
            /**
             * Format: int64
             * @description Per-series override of how long the sweep waits for the pinned group; absent means the global default
             */
            pin_delay_hours?: number;
            /** @description Release group pinned above profile scoring; absent when none */
            pinned_group?: string;
            /** Format: int64 */
            quality_profile_id: number;
            /** @description Provider status (e.g. RELEASING, FINISHED) */
            status?: string;
            title: string;
        };
        SeriesGrabsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SeriesGrabsOutputBody.json
             */
            readonly $schema?: string;
            events: components["schemas"]["GrabEventDTO"][];
            series: string;
        };
        SetMonitoredInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SetMonitoredInputBody.json
             */
            readonly $schema?: string;
            /** @description Whether to monitor the series for downloads */
            monitored: boolean;
        };
        SetMonitoredOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SetMonitoredOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            id: number;
            monitored: boolean;
        };
        SetPinnedGroupInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SetPinnedGroupInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Hours the scheduled sweep waits for this group before taking another (max 8760); omit to use the global default
             */
            delay_hours?: number;
            /** @description Release group to pin above profile scoring; empty clears the pin */
            group: string;
        };
        SetPinnedGroupOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SetPinnedGroupOutputBody.json
             */
            readonly $schema?: string;
            pinned_group?: string;
            /** Format: int64 */
            series_id: number;
        };
        SettingsDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SettingsDTO.json
             */
            readonly $schema?: string;
            auth: components["schemas"]["AuthSettingsDTO"];
            automation: components["schemas"]["AutomationSettingsDTO"];
            download: components["schemas"]["DownloadSettingsDTO"];
            general: components["schemas"]["GeneralSettingsDTO"];
            indexer: components["schemas"]["IndexerSettingsDTO"];
            library: components["schemas"]["LibrarySettingsDTO"];
            notifications: components["schemas"]["NotificationsSettingsDTO"];
        };
        TestDownloadOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TestDownloadOutputBody.json
             */
            readonly $schema?: string;
            /** @example qbittorrent */
            client: string;
            /** @example ok */
            status: string;
        };
        TestOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TestOutputBody.json
             */
            readonly $schema?: string;
            /** @example ok */
            status: string;
        };
        UnscheduledSeriesDTO: {
            /** Format: int64 */
            series_id: number;
            title: string;
        };
        WantedItemDTO: {
            have: boolean;
            /** Format: int64 */
            id: number;
            name?: string;
            /** Format: int64 */
            number: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-activity-history": {
        parameters: {
            query?: {
                /** @description Events per page */
                limit?: number;
                /** @description Opaque cursor from the previous page's next_cursor */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityHistoryOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-activity-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityQueueOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-blocklist-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlocklistSummaryOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "clear-blocklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearedOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "browse-season": {
        parameters: {
            query?: {
                /** @description Season to chart; defaults to the current one */
                season?: "winter" | "spring" | "summer" | "fall";
                /** @description Season year; defaults to the current one */
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowseSeasonOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-calendar": {
        parameters: {
            query: {
                /** @description Range start, inclusive (RFC 3339) */
                start: string;
                /** @description Range end, exclusive (RFC 3339) */
                end: string;
                /** @description Include unmonitored series */
                unmonitored?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "test-download-client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestDownloadOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "search-indexer": {
        parameters: {
            query: {
                /** @description Free-text release search term */
                term: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchIndexerOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "search-metadata": {
        parameters: {
            query: {
                /** @description Title to search AniList for */
                term: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchMetadataOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-quality-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProfilesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-quality-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityProfileDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-quality-profile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Profile id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityProfileDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-quality-profile": {
        parameters: {
            query?: {
                /** @description Profile to move this profile's series to; required when the profile is in use */
                reassign_to?: number;
            };
            header?: never;
            path: {
                /** @description Profile id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSeriesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "add-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSeriesInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetailDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-series": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetailReadDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-series": {
        parameters: {
            query?: {
                /** @description Also remove the series' torrents (and their data) from the download client; otherwise they are left seeding */
                remove_downloads?: boolean;
            };
            header?: never;
            path: {
                /** @description Series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "set-series-monitored": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMonitoredInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetMonitoredOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-series-blocklist": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesBlocklistOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "clear-series-blocklist": {
        parameters: {
            query?: {
                /** @description Clear only the entries whose block has lapsed, keeping what still blocks */
                expired?: boolean;
            };
            header?: never;
            path: {
                /** @description Series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearedOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "clear-series-blocklist-entry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: number;
                /** @description Blocklist entry id */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "grab-series-release": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrabSeriesInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrabSeriesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-series-grabs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesGrabsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "set-series-pinned-group": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPinnedGroupInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetPinnedGroupOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "assign-series-profile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignSeriesProfileInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignSeriesProfileOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "search-series-releases": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id to find releases for */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSeriesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "regenerate-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-automation-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutomationInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-download-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "test-download-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-indexer-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexerInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "test-indexer-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexerInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-library-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "test-library-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-notifications-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationsInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "test-notify-discord": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationsInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "test-notify-ntfy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationsInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "test-notify-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationsInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListJobsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "run-job": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The runner's job name, as reported by list-jobs */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
