/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/browse/season": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chart a broadcast season, served from the per-season cache */
        get: operations["browse-season"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/download/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test connectivity to the configured download client */
        post: operations["test-download-client"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check (public, no API key required) */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexer/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the configured indexer for releases */
        get: operations["search-indexer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search AniList for titles to add */
        get: operations["search-metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List monitored series */
        get: operations["list-series"];
        put?: never;
        /** Add a series by AniList id (expands its wanted items) */
        post: operations["add-series"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a series with its wanted items and their acquisition state */
        get: operations["get-series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update whether a series is monitored */
        patch: operations["set-series-monitored"];
        trace?: never;
    };
    "/api/v1/series/{id}/grab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grab a chosen release: add it to the download client and record it against the wanted items it covers */
        post: operations["grab-series-release"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{id}/grabs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List grab/import history for a series */
        get: operations["list-series-grabs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find and match indexer releases against a series' wanted items (read-only; does not grab) */
        get: operations["search-series-releases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the effective runtime configuration (secrets masked) */
        get: operations["get-settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/apikey/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a new API key (invalidates the old one) */
        post: operations["regenerate-api-key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update the qBittorrent download client (rebuilds it live) */
        put: operations["update-download-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/download/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test qBittorrent connectivity for the given (unsaved) values */
        post: operations["test-download-settings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/indexer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update the Torznab indexer (rebuilds it live) */
        put: operations["update-indexer-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/indexer/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Torznab connectivity for the given (unsaved) values */
        post: operations["test-indexer-settings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update the library import target (rebuilds it live) */
        put: operations["update-library-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/library/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test that the given library directory exists and is writable */
        post: operations["test-library-settings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status of the runner-managed background jobs */
        get: operations["list-jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddSeriesInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AddSeriesInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description AniList media id to add
             */
            anilist_id: number;
            /** @description Whether to monitor for downloads (default true) */
            monitored?: boolean;
        };
        ApiKeyOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ApiKeyOutputBody.json
             */
            readonly $schema?: string;
            api_key: string;
        };
        AuthSettingsDTO: {
            configured: boolean;
            /** @description enabled or local */
            required: string;
            username: string;
        };
        BrowseSeasonOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BrowseSeasonOutputBody.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["SeasonEntryDTO"][];
            /** @enum {string} */
            season: "winter" | "spring" | "summer" | "fall";
            /** Format: int64 */
            year: number;
        };
        CandidateDTO: {
            /** Format: int64 */
            anilist_id: number;
            cover_url?: string;
            english?: string;
            /** Format: int64 */
            episodes: number;
            format?: string;
            native?: string;
            romaji?: string;
            status?: string;
            /** Format: int64 */
            year?: number;
        };
        CandidateReleaseDTO: {
            download_url: string;
            dual_audio: boolean;
            infohash?: string;
            items?: number[];
            matched: boolean;
            reason: string;
            release_group?: string;
            resolution?: string;
            /** Format: int64 */
            seeders: number;
            /** Format: int64 */
            size: number;
            title: string;
        };
        DetailItemDTO: {
            /**
             * Format: date-time
             * @description Broadcast time (RFC 3339, Japanese broadcast clock); absent when the provider publishes none
             */
            airs_at?: string;
            have: boolean;
            /** Format: int64 */
            id: number;
            /** @description Why the last import attempt failed (status stuck) */
            import_error?: string;
            name?: string;
            /** Format: int64 */
            number: number;
            release_title?: string;
            /**
             * @description Derived acquisition state
             * @enum {string}
             */
            status: "have" | "downloading" | "stuck" | "deferred" | "wanted";
        };
        DownloadInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DownloadInputBody.json
             */
            readonly $schema?: string;
            category?: string;
            /** @description Leave empty to keep the stored password */
            password?: string;
            url?: string;
            user?: string;
        };
        DownloadSettingsDTO: {
            category: string;
            configured: boolean;
            password_set: boolean;
            url: string;
            user: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][];
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        GeneralSettingsDTO: {
            addr: string;
            /** @description Current API key (visible to authenticated callers) */
            api_key: string;
            data_dir: string;
            db_path: string;
            version: string;
        };
        GrabEventDTO: {
            created_at: string;
            /** Format: int64 */
            id: number;
            infohash: string;
            /** Format: int64 */
            item_number: number;
            /** @description Why the last import attempt failed, while still grabbed */
            last_error?: string;
            release_title: string;
            /** @description grabbed, imported, import_deferred, or failed */
            status: string;
        };
        GrabSeriesInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GrabSeriesInputBody.json
             */
            readonly $schema?: string;
            /** @description download_url of a matched release from the series search */
            download_url: string;
            /** @description Add the torrent stopped (no data transfer) — useful for testing the grab flow */
            paused?: boolean;
        };
        GrabSeriesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GrabSeriesOutputBody.json
             */
            readonly $schema?: string;
            /** @description Set when the grabbed release falls outside the series' quality profile — informational, the grab still succeeds */
            ineligible_reason?: string;
            infohash: string;
            items: number[];
            /** @example success */
            outcome: string;
            release: string;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /** @example ok */
            status: string;
            version: string;
        };
        IndexerInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/IndexerInputBody.json
             */
            readonly $schema?: string;
            /** @description Leave empty to keep the stored API key */
            apikey?: string;
            name?: string;
            url?: string;
        };
        IndexerSettingsDTO: {
            apikey_set: boolean;
            configured: boolean;
            name: string;
            url: string;
        };
        JobStatusDTO: {
            /** Format: int64 */
            interval_ms: number;
            /**
             * Format: double
             * @description Fractional: a sub-millisecond sweep would otherwise always report 0
             */
            last_duration_ms: number;
            last_error?: string;
            /** @description RFC3339 UTC; absent until the job has run */
            last_run?: string;
            name: string;
            /** @description RFC3339 UTC; absent while the runner is not running */
            next_run?: string;
            running: boolean;
        };
        LibraryInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LibraryInputBody.json
             */
            readonly $schema?: string;
            dir?: string;
            /** @enum {string} */
            mode?: "auto" | "hardlink" | "copy";
        };
        LibrarySettingsDTO: {
            configured: boolean;
            dir: string;
            mode: string;
        };
        ListJobsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListJobsOutputBody.json
             */
            readonly $schema?: string;
            jobs: components["schemas"]["JobStatusDTO"][];
        };
        ListSeriesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListSeriesOutputBody.json
             */
            readonly $schema?: string;
            series: components["schemas"]["SeriesDTO"][];
        };
        ReleaseDTO: {
            download_url: string;
            indexer: string;
            infohash?: string;
            /** Format: int64 */
            seeders: number;
            /** Format: int64 */
            size: number;
            title: string;
        };
        SearchIndexerOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SearchIndexerOutputBody.json
             */
            readonly $schema?: string;
            results: components["schemas"]["ReleaseDTO"][];
        };
        SearchMetadataOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SearchMetadataOutputBody.json
             */
            readonly $schema?: string;
            results: components["schemas"]["CandidateDTO"][];
        };
        SearchSeriesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SearchSeriesOutputBody.json
             */
            readonly $schema?: string;
            results: components["schemas"]["CandidateReleaseDTO"][];
            series: string;
            term: string;
        };
        SeasonEntryDTO: {
            /** Format: int64 */
            anilist_id: number;
            /** Format: int64 */
            average_score: number;
            cover_url?: string;
            english?: string;
            /** Format: int64 */
            episodes: number;
            format?: string;
            genres?: string[];
            native?: string;
            /** Format: date-time */
            next_airs_at?: string;
            /** Format: int64 */
            next_episode?: number;
            /** Format: int64 */
            popularity: number;
            romaji?: string;
            status?: string;
            studio?: string;
        };
        SeriesDTO: {
            format: string;
            /** Format: int64 */
            have: number;
            /** Format: int64 */
            id: number;
            monitored: boolean;
            title: string;
            /** Format: int64 */
            total: number;
        };
        SeriesDetailDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SeriesDetailDTO.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            anilist_id: number;
            format: string;
            /** Format: int64 */
            id: number;
            items: components["schemas"]["WantedItemDTO"][];
            monitored: boolean;
            title: string;
        };
        SeriesDetailReadDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SeriesDetailReadDTO.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            anilist_id?: number;
            english?: string;
            format: string;
            /** Format: int64 */
            id: number;
            items: components["schemas"]["DetailItemDTO"][];
            monitored: boolean;
            native?: string;
            /** @description Provider status (e.g. RELEASING, FINISHED) */
            status?: string;
            title: string;
        };
        SeriesGrabsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SeriesGrabsOutputBody.json
             */
            readonly $schema?: string;
            events: components["schemas"]["GrabEventDTO"][];
            series: string;
        };
        SetMonitoredInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SetMonitoredInputBody.json
             */
            readonly $schema?: string;
            /** @description Whether to monitor the series for downloads */
            monitored: boolean;
        };
        SetMonitoredOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SetMonitoredOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            id: number;
            monitored: boolean;
        };
        SettingsDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SettingsDTO.json
             */
            readonly $schema?: string;
            auth: components["schemas"]["AuthSettingsDTO"];
            download: components["schemas"]["DownloadSettingsDTO"];
            general: components["schemas"]["GeneralSettingsDTO"];
            indexer: components["schemas"]["IndexerSettingsDTO"];
            library: components["schemas"]["LibrarySettingsDTO"];
        };
        TestDownloadOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TestDownloadOutputBody.json
             */
            readonly $schema?: string;
            /** @example qbittorrent */
            client: string;
            /** @example ok */
            status: string;
        };
        TestOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TestOutputBody.json
             */
            readonly $schema?: string;
            /** @example ok */
            status: string;
        };
        WantedItemDTO: {
            have: boolean;
            /** Format: int64 */
            id: number;
            name?: string;
            /** Format: int64 */
            number: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "browse-season": {
        parameters: {
            query?: {
                /** @description Season to chart; defaults to the current one */
                season?: "winter" | "spring" | "summer" | "fall";
                /** @description Season year; defaults to the current one */
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowseSeasonOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "test-download-client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestDownloadOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "search-indexer": {
        parameters: {
            query: {
                /** @description Free-text release search term */
                term: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchIndexerOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "search-metadata": {
        parameters: {
            query: {
                /** @description Title to search AniList for */
                term: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchMetadataOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSeriesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "add-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSeriesInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetailDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-series": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetailReadDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "set-series-monitored": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMonitoredInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetMonitoredOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "grab-series-release": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrabSeriesInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrabSeriesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-series-grabs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesGrabsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "search-series-releases": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id to find releases for */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSeriesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "regenerate-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-download-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "test-download-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-indexer-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexerInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "test-indexer-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexerInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-library-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "test-library-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListJobsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
